<?php
/**
 * This Software is the property of Data Development and is protected
 * by copyright law - it is NOT Freeware.
 * Any unauthorized use of this software without a valid license
 * is a violation of the license agreement and will be prosecuted by
 * civil and criminal law.
 * https://www.shopmodule.com
 *
 * @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
 * @author        D3 Data Development <support@shopmodule.com>
 * @link          https://www.oxidmodule.com
 */

$sLangName = "English";
$iLangNr   = 1;
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(

    //Tabs

    //Navigation
    'charset'                                                            => 'ISO-8859-15',
    'd3mximporter'                                                       => '<i class="fas fa-fw fa-database"></i> Importer',
    'd3mxarticleimport'                                                  => 'Article import',
    'd3mximporter_cfg'                                                   => 'Settings',
    'd3mximporter_cfg_main'                                              => 'Main',
    'd3tbclimporter_cfg_main'                                            => 'Settings',
    'd3tbclimporter_main'                                                => 'Main',
    'd3tbclimporter_fields'                                              => 'Article fields',
    'd3tbclimporter_category'                                            => 'Categories',
    'd3tbclimporter_cross'                                               => 'Crossselling',
    'd3tbclimporter_attrib'                                              => 'Attributes',
    'd3tbclimporter_selectlist'                                          => 'Select lists',
    'd3tbclimporter_variants'                                            => 'Variants',
    'd3tbclimporter_price2art'                                           => 'Scale prices',
    'd3tbclimporter_vendors'                                             => 'Manufacturer',
    'd3tbclimporter_config'                                              => 'Config.',
    'd3tbclimporter_mall'                                                => 'Mall',
    'd3tbclimporter_import'                                              => 'Import',
    'd3tbclimporter_afterimport'                                         => 'After import',
    'd3mxpictureimport'                                                  => 'Picture import',
    'd3tbclpicture_main'                                                 => 'Main',
    'd3tbclpicture_import'                                               => 'Import',
    'D3_IMPORTER_METADATA_ALTITLE'                                       => 'D³ Importer',
    'D3_IMPORTER_METADATA_ALDESC'                                        => '--',
    'D3_IMPORTER_METADATA_AUTHOR'                                        => 'D³ Data Development, Inh. Thomas Dartsch',
    'D3_TOOLTIPS_NEWIMPORTPROFIL'                                        => 'New Profile',
    'D3_IMPORTER_CFG_LIST_SETTLANG'                                      => 'Language setting',
    'D3_IMPORTER_CFG_MAIN_TITLE'                                         => 'Importer - Settings',
    'D3_IMPORTER_MENUITEM'                                               => 'Importer',
    'D3_IMPORTER_ROW'                                                    => 'Row',
    'D3_IMPORTER_ROW_OF'                                                 => 'of',
    'D3_IMPORTER_LIST_MENUSUBITEM'                                       => 'Article import',
    'D3_PICTURE_LIST_MENUSUBITEM'                                        => 'Picture import',
    'D3_IMPORTER_MAIN_OXID'                                              => 'Profile-ID',
    'D3_IMPORTER_MAIN_DESCRIPTION'                                       => 'Profile name',
    'D3_IMPORTER_MAIN_IMPORTFILE'                                        => 'Import file',
    'D3_IMPORTER_MAIN_NOFILE'                                            => '-- none --',
    'D3_IMPORTER_MAIN_NEWFILE'                                           => 'Upload new file (max. file size: %1$s)',
    'D3_IMPORTER_MAIN_ALLOWEXT_MAXFILESIZE_HELP'                         => 'permitted filetypes "csv" or "txt"',
    'D3_IMPORTER_MAIN_EXCEEDS_MAXFILESIZE'                               => '"${filename}" exceeds the maximum file size of ${maxfilesize}.',
    'D3_IMPORTER_MAIN_COLSEP'                                            => 'Fields separated by:',
    'D3_IMPORTER_MALL_COLUMSEPARATOR_MALL_HELP'                          => 'e.g. ; or TAB (TAB = Tabulator)',
    'D3_IMPORTER_MAIN_TEXTSEP'                                           => 'Fields enclosed by (optional):',
    'D3_IMPORTER_MAIN_TEXTSEPDESCRIPTION_HELP'                           => 'e.g. \' or "',
    'D3_IMPORTER_MAIN_FIFELINFO_HEAD'                                    => 'File info',
    'D3_IMPORTER_MAIN_FIFELINFO_NAME'                                    => 'Name',
    'D3_IMPORTER_MAIN_FIFELINFO_SIZE'                                    => 'Size',
    'D3_IMPORTER_MAIN_FIFELINFO_CHANGE'                                  => 'Last change',
    'D3_IMPORTER_MAIN_FIFELINFO_READ'                                    => 'Readable',
    'D3_IMPORTER_MAIN_FIFELINFO_WRITE'                                   => 'Writeable',
    'D3_IMPORTER_MAIN_FIFELINFO_CSV'                                     => 'CSV',
    'D3_IMPORTER_MAIN_FIFELINFO_ROWS'                                    => 'Rows',
    'D3_IMPORTER_MAIN_FIFELINFO_COLUMS'                                  => 'Columns',
    'D3_IMPORTER_MAIN_FIFELINFO_RIGHTS'                                  => 'Linux-Rights',
    'D3_IMPORTER_MAIN_FIFELINFO_OWNER'                                   => 'Owner',
    'D3_IMPORTER_MAIN_FIFELINFO_GROUP'                                   => 'Group',
    'D3_IMPORTER_FIELDS_COLUM'                                           => 'Column',
    'D3_IMPORTER_FIELDS_COLUMASSIGN'                                     => 'Column content and assignment',
    'D3_IMPORTER_FIELDS_UPDATE'                                          => 'Update',
    'D3_IMPORTER_FIELDS_INFOTEXT_HELP'                                   => 'Should a column also used for article update, please mark the corresponding Checkbox "Update". <br>',
    'D3_IMPORTER_FIELDS_XXXX'                                            => 'Advice: <b>Assignment of article identification is mandatory!</b>',
    'D3_IMPORTER_FIELDS_XXXX_HELP'                                       => 'In tab "config." you assign the article identification.<br>In tab "Article fields" the article identification must be also assigned.<br><br>f.i.: oxartnum (article number)',
    'D3_IMPORTER_CATEGORY_ASSIGN'                                        => 'Category field assignment',
    'D3_IMPORTER_CATEGORY_NOASSIGN'                                      => '-- none --',
    'D3_IMPORTER_CATEGORY_ASSIGNINFO_HELP'                               => '<b>Compulsory field!</b> Define here, which field should be checked as reference.<br><br>Notice: Only if the reference is set to "title (oxtitle)" the importer will create the category structure if non-existing.',
    'D3_IMPORTER_CATEGORY_ASSIGN_NEEDED'                                 => '<b>Compulsory field!</b>',
    'D3_IMPORTER_CATEGORY_IMPORTTYPE'                                    => 'Importtyp',
    'D3_IMPORTER_CATEGORY_IMPORTTYPE1'                                   => 'Only import',
    'D3_IMPORTER_CATEGORY_IMPORTTYPE2'                                   => 'Delete article-cat.-assignment before',
    'D3_IMPORTER_CATEGORY_IMPORTTYPEINFO_HELP'                           => '"Only import" = Categories will be imported or rather assigned to article.<br>"Delete before" = All category assignments of current article will be deleted before update.',
    'D3_IMPORTER_CATEGORY_IMPORTCOLUM'                                   => 'Column assignment',
    'D3_IMPORTER_CATEGORY_COLSEP'                                        => 'Internal field separation',
    'D3_IMPORTER_CATEGORY_IMPORTCOLUMINFO_HELP'                          => 'Assigns category field of this import column to current article.',
    'D3_IMPORTER_CROSS_IMPORTTYPE'                                       => 'Crossselling importtyp',
    'D3_IMPORTER_CROSS_IMPORTTYPE1'                                      => 'Only import',
    'D3_IMPORTER_CROSS_IMPORTTYPE2'                                      => 'Delete article-crosssell.-assignment before',
    'D3_IMPORTER_CROSS_IMPORTTYPEINFO_HELP'                              => '"Only import" = crossselling will be assigned to article<br>"Delete before" = all crossselling assignments of current article will be deleted before update.',
    'D3_IMPORTER_CROSS_NOASSIGN'                                         => '-- none --',
    'D3_IMPORTER_CROSS_IMPORTCOLUM'                                      => 'Column assignment',
    'D3_IMPORTER_CROSS_IMPORTCOLUMINFO_HELP'                             => 'Assigns crossselling field of this import column to current article.',
    'D3_IMPORTER_CROSS_COLSEP'                                           => 'Internal column separation',
    'D3_IMPORTER_MALL_IMPORTCOLUM_MALL'                                  => 'Column assignment',
    'D3_IMPORTER_MALL_IMPORTCOLUM_MALL_HELP'                             => 'Assigns article2shop information of this import column to current article.',
    'D3_IMPORTER_MALL_COLUMSEPARATOR_MALL'                               => 'Internal column separation',
    'D3_IMPORTER_ACC_IMPORTTYPE'                                         => 'Accessoire importtyp',
    'D3_IMPORTER_ACC_IMPORTTYPE1'                                        => 'Only import',
    'D3_IMPORTER_ACC_IMPORTTYPE2'                                        => 'Delete article-accessoire-assignments before',
    'D3_IMPORTER_ACC_IMPORTTYPEINFO_HELP'                                => '"Only import" = accessoire will be assigned to article<br>"Delete before" = all accessoire assignments of urrent article will be deleted before.',
    'D3_IMPORTER_ACC_NOASSIGN'                                           => '-- none --',
    'D3_IMPORTER_ACC_IMPORTCOLUM'                                        => 'Column assignment',
    'D3_IMPORTER_ACC_IMPORTCOLUMINFO_HELP'                               => 'Assigns accessoire field of this import column to current article.',
    'D3_IMPORTER_ACC_COLSEP'                                             => 'Internal column separation',
    'D3_IMPORTER_ATTRIB_IMPORTTYPE'                                      => 'Attributes importtyp',
    'D3_IMPORTER_ATTRIB_IMPORTTYPE1'                                     => 'Only import',
    'D3_IMPORTER_ATTRIB_IMPORTTYPE2'                                     => 'Delete article-attribute-assignment before',
    'D3_IMPORTER_ATTRIB_IMPORTTYPEINFO_HELP'                             => '"Only import" = attributes will be assigned to article<br>"Delete before" = all attribute assignments of current article will be deleted before.',
    'D3_IMPORTER_ATTRIB_NOASSIGN'                                        => '-- none --',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM'                                     => 'Column assignment',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUMINFO_HELP'                            => 'Assigns attributes field of this import column to current article.',
    'D3_IMPORTER_ATTRIB_COLSEP1'                                         => 'Attribute separation',
    'D3_IMPORTER_ATTRIB_COLSEPDESCRIPTION1_HELP'                         => 'Define a separator, if the column contains multiple attributes. (e.g. "Material|Surface") then "|"',
    'D3_IMPORTER_ATTRIB_COLSEP2'                                         => 'Value separator',
    'D3_IMPORTER_ATTRIB_COLSEPDESCRIPTION2_HELP'                         => 'Define a separator, if the column contains further attribute values. (e.g. "Material,Aluminium|Surface,matt|...") then ","',
    'D3_IMPORTER_SELECTLIST_IMPORTTYPE'                                  => 'Select lists importtyp',
    'D3_IMPORTER_SELECTLIST_IMPORTTYPE1'                                 => 'Only import',
    'D3_IMPORTER_SELECTLIST_IMPORTTYPE2'                                 => 'Delete all select lists before',
    'D3_IMPORTER_SELECTLIST_IMPORTTYPEINFO_HELP'                         => '"Only import" = a new selectlist will be created and assigned to the article.<br>"Delete all select lists before" = all select list assignments of current article will be deleted before.',
    'D3_IMPORTER_SELECTLIST_NOASSIGN'                                    => '-- none --',
    'D3_IMPORTER_SELECTLIST_NAME'                                        => 'Title of select list',
    'D3_IMPORTER_SELECTLIST_ALTNAME'                                     => 'Alternative title',
    'D3_IMPORTER_SELECTLIST_VALUE'                                       => 'Select fields',
    'D3_IMPORTER_SELECTLIST_SEPARATOR'                                   => 'Value separator',
    'D3_IMPORTER_SELECTLIST_PRICESEPARATOR'                              => 'Price separator',
    'D3_IMPORTER_SELECTLIST_TITLE_HELP'                                  => '"Title of select list" = Define the csv-importfield, where the title, e.g. "Color", is stored.',
    'D3_IMPORTER_SELECTLIST_ALTTITLE_HELP'                               => '"Alternative title" = If it is no field for "title of select list", or the content is partially empty, so you can define an alternative title e.g. "Select".',
    'D3_IMPORTER_SELECTLIST_SELECTFIELDS_HELP'                           => '"Selectfields" = csv-import field with values of select list',
    'D3_IMPORTER_SELECTLIST_SEPARATOR_HELP'                              => '"Value separator" = If there ar more values in csv-import field "Selectfields", you have to define which separator is used. e.g. "@" if the csv contains "red@yellow@green..."',
    'D3_IMPORTER_SELECTLIST_PRICESEPARATOR_HELP'                         => '"Price separator" = In addition you can import price changes (fix and %). e.g. "red|2,34@yellow|5%@grün|1,23...". In this example the value separator is "@" and the price separator is "|".',
    'D3_IMPORTER_SELECTLIST_INFOTEXT'                                    => 'You can import as many select lists as you like, with as many values as you like for every article.',
    'D3_IMPORTER_VARIANTS_IMPORTTYPE'                                    => 'Variants importtyp',
    'D3_IMPORTER_VARIANTS_IMPORTTYPE1'                                   => 'Only import',
    'D3_IMPORTER_VARIANTS_IMPORTTYPE2'                                   => 'Delete variants before',
    'D3_IMPORTER_VARIANTS_IMPORTTYPEINFO'                                => '"Only import" = Variants will be reassigned or updated to parent article.<br>"Delete before" = All variant-article-assignments of current parent article will be deleted before update.',
    'D3_IMPORTER_VARIANTS_NOASSIGN'                                      => '-- none --',
    'D3_IMPORTER_VARIANTS_IMPORTCOLUM'                                   => 'Variants identification',
    'D3_IMPORTER_VARIANTS_IMPORTCOLUMINFO'                               => 'The column with article identification of parent article, will be assigned.',
    'D3_IMPORTER_PRICE2ART_IMPORTTYPE'                                   => 'Importtyp',
    'D3_IMPORTER_PRICE2ART_IMPORTTYPE1'                                  => 'Only import',
    'D3_IMPORTER_PRICE2ART_IMPORTTYPE2'                                  => 'Delete scale prices before',
    'D3_IMPORTER_PRICE2ART_IMPORTTYPEINFO_HELP'                          => '"Only import" = Scale prices will be reassigned or updated to current article.<br>"Delete before" = All scale prices of current article will be deleted before update.',
    'D3_IMPORTER_PRICE2ART_PRICE'                                        => 'Scale price',
    'D3_IMPORTER_PRICE2ART_AMOUNTFROM'                                   => 'Quantity from',
    'D3_IMPORTER_PRICE2ART_AMOUNTTO'                                     => 'Quantity to',
    'D3_IMPORTER_VENDORS_IMPORTTYPE'                                     => 'Create distributors',
    'D3_IMPORTER_VENDORS_IMPORTTYPE1'                                    => 'Yes',
    'D3_IMPORTER_VENDORS_IMPORTTYPE2'                                    => 'No, only assignment',
    'D3_IMPORTER_VENDORS_IMPORTTYPEINFO_HELP'                            => '"Yes" = If the distributor does not exists, he will be added and assigned to article.<br>"Only import" = The article will be assigned only to a existing distributor.',
    'D3_IMPORTER_VENDORS_ASSIGN'                                         => 'Distributor import column',
    'D3_IMPORTER_VENDORS_NOASSIGN'                                       => '-- none --',
    'D3_IMPORTER_VENDORS_ASSIGNINFO_HELP'                                => 'The column with name of distributor will be assigned.',
    'D3_IMPORTER_MANUFACTURER_IMPORTTYPE'                                => 'Create manufacturer',
    'D3_IMPORTER_MANUFACTURER_IMPORTTYPE1'                               => 'Yes',
    'D3_IMPORTER_MANUFACTURER_IMPORTTYPE2'                               => 'No, only assignment',
    'D3_IMPORTER_MANUFACTURER_IMPORTTYPEINFO_HELP'                       => '"Yes" = If the manufacturer does not existsp, he will be added and assigned to article.<br>"Only import" = The article will be assigned only to a existing manufacturer.',
    'D3_IMPORTER_MANUFACTURER_ASSIGN'                                    => 'Manufacturer import column',
    'D3_IMPORTER_MANUFACTURER_NOASSIGN'                                  => '-- none --',
    'D3_IMPORTER_MANUFACTURER_ASSIGNINFO_HELP'                           => 'The column with name of manufacturer will be assigned.',
    'D3_IMPORTER_CONFIG_MAINOPTIONS'                                     => 'Core settings',
    'D3_IMPORTER_MALL_MAINOPTIONS'                                       => 'settings',
    'D3_IMPORTER_CONFIG_IMPORTTYPE'                    => 'Importtype',
    'D3_IMPORTER_CONFIG_IMPORTTYPE_STANDARD'           => 'Import and update',
    'D3_IMPORTER_CONFIG_IMPORTTYPE_IMPORT'             => 'Only import',
    'D3_IMPORTER_CONFIG_IMPORTTYPE_UPDATE'             => 'Only update',
    'D3_IMPORTER_CONFIG_OMITLINES'                     => 'Number of data headlines (will not be imported)',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT'                   => 'Article identification',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_HELP'              => 'Define a <b>clear</b> article identification, so that no duplicates occur.' //
        .'<br>The elected field has to be assigned to a import column in "Article fields".' //
        .'<br>Default is the article number.' //
        .'<br>The fields can be configured in "importer/settings/Settings/Settings/article identification".',
    'D3_IMPORTER_CONFIG_PRICEOPTIONS'                                    => 'Price options',
    'D3_IMPORTER_CONFIG_PRICEPLUSPERCENT'              => 'Raise imported article price by x%.',
    'D3_IMPORTER_CONFIG_PRICEDECIMALROUND'             => 'Round imported article price to x decimal places.',
    'D3_IMPORTER_CONFIG_IDENTOPTIONS'                                    => 'Article-ident options (Expert mode)',
    'D3_IMPORTER_CONFIG_ARTNUM2OXID'                   => 'Use article identification field as ident (datafield &quot;oxid&quot;).',
    'D3_IMPORTER_CONFIG_MD54OXID'                      => 'Encode the ident field additionaly with MD5. ',
    'D3_IMPORTER_IMPORT_START'                                           => 'Start article import!',
    'D3_IMPORTER_IMPORT_INFO1'                                           => 'Imported rows',
    'D3_IMPORTER_IMPORT_INFO2'                                           => 'from',
    'D3_IMPORTER_IMPORT_IMPORTEND'                                       => 'Import finished.',
    'D3_IMPORTER_IMPORT_STATISTICHEAD'                                   => 'Result (incl. variants):',
    'D3_IMPORTER_IMPORT_STATISTIC1'                                      => 'Importierted articles:',
    'D3_IMPORTER_IMPORT_STATISTIC2'                                      => 'Updated articles:',
    'D3_IMPORTER_AFTERIMPORT_PREINFO0'                                   => 'articles are changed with this profile in the past.',
    'D3_IMPORTER_AFTERIMPORT_PREINFO1'                                   => 'articles ',
    'D3_IMPORTER_AFTERIMPORT_PREINFO2'                                   => 'were not imported or updated during the last import.',
    'D3_IMPORTER_AFTERIMPORT_PREINFO3'                                   => 'Now, you can have these articles deactivated or deleted.',
    'D3_IMPORTER_AFTERIMPORT_TICKER'                                     => 'Articles per run',
    'D3_IMPORTER_AFTERIMPORT_MAINARTICLE'                                => 'Main articles',
    'D3_IMPORTER_AFTERIMPORT_VARIANTS'                                   => 'Variants',
    'D3_IMPORTER_AFTERIMPORT_DOINACTIVE'                                 => 'Deactivate all articles',
    'D3_IMPORTER_AFTERIMPORT_DODELETE'                                   => 'Delete all articles',
    'D3_IMPORTER_AFTERIMPORT_INFO1'                                      => 'Edited articles',
    'D3_IMPORTER_AFTERIMPORT_INFO2'                                      => 'from',
    'D3_IMPORTER_AFTERIMPORT_IMPORTEND'                                  => 'After import is finished.',
    'D3_IMPORTER_FAILUPLOAD_10'                                          => 'Error: File incorrect, empty or uploaded incompletly.',
    'D3_IMPORTER_FAILUPLOAD_11'                                          => 'Error: Forbidden file extension.',
    'D3_IMPORTER_FAILUPLOAD_12'                                          => 'Error: Target directory was not found.',
    'D3_IMPORTER_FAILUPLOAD_13'                                          => 'Error: File could not be saved in target directory.(insufficient writing ?)',
    'D3_IMPORTER_FAILUPLOAD_20'                                          => 'Error: No licence or modul inactive!',
    'D3_IMPORTER_FAILCONFIG_10'                                          => 'Error: No profile loaded!',
    'D3_IMPORTER_FAILCONFIG_11'                                          => 'Error: No import file elected!',
    'D3_IMPORTER_FAILCONFIG_12'                                          => 'Error: Importfile incorrect or empty!',
    'D3_IMPORTER_FAILCONFIG_13'                                          => 'Error: No separator set!',
    'D3_IMPORTER_FAILCONFIG_14'                                          => 'Error: Importfile incorrect or empty!',
    'D3_IMPORTER_FAILCONFIG_15'                                          => 'Error: No "after-import" action defined.',
    'D3_IMPORTER_FAILCONFIG_20'                                          => 'Error: No licence or modul inactive!',
    'D3_IMPORTER_FAILIMPORT_10'                                          => 'Error: Import file could not be loaded!',
    'D3_IMPORTER_FAILIMPORT_11'                                          => 'Error: Field for article identification was not assigned in tab "article fields" or in tab "Config."!',
    'D3_IMPORTER_FAILIMPORT_12'                                          => 'Error: No or invalid "after-import" action defined.',
    'D3_IMPORTER_FAILIMPORT_20'                                          => 'Error: No licence or modul inactive!',
    'D3_PICTURE_IMPORTFIELD'                                             => 'Import',
    'D3_PICTURE_IMPORTFIELD_OXPIC'                                       => 'picture',
    'D3_PICTURE_IMPORTFIELD_OXZOOM'                                      => 'zoom',
    'D3_PICTURE_NOASSIGN'                                                => '-- none --',
    'D3_PICTURE_FAILCONFIG_10'                                           => 'Error: No profile loaded!',
    'D3_PICTURE_FAILCONFIG_11'                                           => 'Error: Picture-import directory was not found!',
    'D3_PICTURE_FAILCONFIG_12'                                           => 'Error: Picture-import directory could not be read!',
    'D3_PICTURE_FAILCONFIG_13'                                           => 'Error: No files found in picture-import directory!',
    'D3_PICTURE_FAILCONFIG_14'                                           => 'Error: Import file incorret or empty!',
    'D3_PICTURE_FAILCONFIG_20'                                           => 'There were no external picture-Urls found in import fields of article table.<br>This is no error, if you didn`t want to import pictures from an external source or you have already done this completely.',
    'D3_PICTURE_FAILCONFIG_30'                                           => 'Error: No licence or modul inactive!',
    'D3_PICTURE_IMPORT_INFO_1'                                           => 'Directory-info:',
    'D3_PICTURE_IMPORT_INFO_2'                                           => 'Picture files:',
    'D3_PICTURE_IMPORT_INFO_3'                                           => 'Already edited:',
    'D3_PICTURE_IMPORT_INFO_4'                                           => 'Therefrom imported:',
    'D3_PICTURE_IMPORT_NOTICE_1'                                         => 'Notice:<br>No picture files were found in picture import-directory. First you have to read in the picture directory again, then you can do a picture import.',
    'D3_PICTURE_IMPORT_NOTICE_2'                                         => 'Notice:<br>All pictures, which were read in before, were edited on a previous picture import.<br>If you want to start a new picture import, so read in the picture import-directory again.',
    'D3_PICTURE_IMPORT_NOTICE_3'                                         => 'Notice:<br>Some pictures have already been edited. You can do picture import with the rest of the pictures.<br>Or you read in the picture import-directory again. In this case, it will be attempted to import all pictures.',
    'D3_PICTURE_IMPORT_NOTICE_4'                                         => 'Notice:<br>If you have copied new pictures to picture import-directory,<br>please read in picture import-directory again, update the number of pictures.',
    'D3_PICTURE_SCANDIR_START'                                           => 'Read in picture-import directory',
    'D3_PICTURE_EXTPICTURE_START'                                        => 'Read in external pictures',
    'D3_PICTURE_IMPORT_START'                                            => 'Start picture-import!',
    'D3_PICTURE_IMPORT_INFO1'                                            => 'Edited pictures',
    'D3_PICTURE_IMPORT_INFO2'                                            => 'from',
    'D3_PICTURE_IMPORT_INFO3'                                            => 'Therefrom imported ',
    'D3_PICTURE_IMPORT_IMPORTEND'                                        => 'Picture import finished.',
    'D3_PICTURE_EXTIMPORT_INFO1'                                         => 'Edited external picture-Urls',
    'D3_PICTURE_EXTIMPORT_IMPORTEND'                                     => 'External picture import finished. The actual picture import could be started now.',
    'D3_PICTURE_IMPORT_ERRORPRETEXT'                                     => 'Error in:',
    'D3_PICTURE_IMPORT_ERRORTYPE_10'                                     => 'No valid picture url',
    'D3_PICTURE_IMPORT_ERRORTYPE_20'                                     => 'CURL connect error',
    'D3_PICTURE_IMPORT_ERRORTYPE_30'                                     => 'No valid picture name',
    'D3_PICTURE_IMPORT_ERRORTYPE_40'                                     => 'No valid picture type',
    'D3_IMPORTER_PICTURE_CHOOSE_PROFILE'                                 => 'Please choose your import profile.',
    'D3_IMPORTER_EXPORTCONFIG'                                           => 'export importprofile',
    'D3_IMPORTER_MAIN_MAINSETTINGS'                                      => 'Settings',
    'D3_IMPORTER_MAIN_ARTICLEINDENTIFICATIONFIELDS'                      => 'article identification',
    'D3_IMPORTER_MAIN_ARTICLEINDENTIFICATIONFIELDS_HELP'                 => 'Select multiple fields with the key CTRL, to provide the selection in /D³ Module/Importer/article import/Config./article identification/',
    'D3_IMPORTER_CONFIG_ATRUESETTINGS'                 => 'definition of "yes" values',
    'D3_IMPORTER_CONFIG_AFALSESETTINGS'                => 'definition of "no" values',
    'D3_IMPORTER_CONFIG_ATRUESETTINGS_HELP'            => 'There can be different values for an active check in a CSV file.' //
        . '<br> F.e.: Yes/No, true/false, 1/0, y/n, active/inactive.' //
        . '<br>Enter the values line by line thereby the import process can interpret the given values.' //
        . '<br><br>The import process checks the following criteria:' //
        . '<ul><li>the values will handled in case sensitive<li>' //
        . '<li>numbers will interpreted as numbers: "1" is not the string "one"<li>' //
        . '</ul>' //
        . 'given values:<br>' //
        . 'Yes field:<br>true<br>TRUE',
    'D3_IMPORTER_CONFIG_AFALSESETTINGS_HELP'           => 'There can be different values for an active check in a CSV file.' //
        . '<br> F.e.: Yes/No, true/false, 1/0, y/n, active/inactive.' //
        . '<br>Enter the values line by line thereby the import process can interpret the given values.' //
        . '<br><br>The import process checks the following criteria:' //
        . '<ul><li>the values will handled in case sensitive<li>' //
        . '<li>numbers will interpreted as numbers: "1" is not the string "one"<li>' //
        . '</ul>' //
        . 'given values:<br>' //
        . 'No field:<br>false<br>FALSE',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_CHOOSE'                              => 'please choose!',
    'D3_IMPORTER_PICTURE_PICSPERTICK'                                    => 'Start next run of pictures:',
    'D3_IMPORTER_PICTURE_PICSPERTICK_HELP'                               => 'The process of a picture import is as follows:' //
        . '<br>1. All pictures from picture import directory will be read.' //
        . '<br>2. Looks for a relation in database (oxarticles_d3importpic1-XX) per picture(name).' //
        . '<br>3. In case of one or more hits, the picture(s) will be imported and assigned to the article(s).',
    'D3_IMPORTER_PICTURE_MAXPICTURECOUNT'                                => 'after',
    'D3_IMPORTER_PICTURE_MAXPICTURECOUNT_2'                              => 'read pictures',
    'D3_IMPORTER_PICTURE_MAXPICTURECOUNT_HELP'                           => 'After x read pictures the run will be restarted (if no pictures were imported).',
    'D3_IMPORTER_PICTURE_MAXIMPORTCOUNT'                                 => 'or after',
    'D3_IMPORTER_PICTURE_MAXIMPORTCOUNT_2'                               => 'imported pictures',
    'D3_IMPORTER_PICTURE_MAXIMPORTCOUNT_HELP'                            => 'After x imported pictures the run will be restarted (concerns only imported pictures).',
    'D3_IMPORTER_FAILTOSAVE_DUE_DEMO'                                    => 'error: module is in demo mode and has reached the limit of profiles',
    'D3_IMPORTER_NOTICE_PROFILELIMITREACHED'                             => 'notice: the module is in demo mode and has reached the limit of profiles.<br> you can\'t save another one.',
    'D3_IMPORTER_CONFIG_AARTICLESETTINGS'              => 'predefined values for articlefields',
    'D3_IMPORTER_CONFIG_AARTICLESETTINGS_HELP'         => 'Insert predefined values, which fill the <u title="The field names can be seen in the database table oxarticles.">articlefields</u> with the specific values during the import process.' //
        . '<h4>following criteria are applied:</h4><ul><li>The notation is "FIELDNAME => VALUE".</li>' //
        . '<li>If the CSV value is associated with the predefined field and the CSV value is filled, the value from the CSV file will be saved at the article.</li></ul>' //
        . '<h4>Example 1:</h4> All imported articles should have a stock of 10:<br> oxstock => 10' //
        . '<h4>Example 2:</h4> All imported articles should be set to inactive:<br> oxactive => 0' //
        . '<h4>Example 3:</h4> All imported articles should be set to inactive and should have a stock of 10:<br> oxactive => 0<br>oxstock => 10',
    'D3_IMPORTER_CONFIG_IMPORTTICKER'                  => 'Lines per Run',
    'D3_IMPORTER_CONFIG_FILEHEADERCOUNT'                                 => 'Number of Headerlines',
    'D3_IMPORTER_CONFIG_FILEHEADERCOUNT_HELP'                            => 'How many lines should not be importet. ' //
        . 'For Example: The fist line of your CSV-File include the description of the filddata, than you should use 1.',
    'D3_IMPORTER_MAIN_CATEGORIE_INDENTIFICATIONFIELDS'                   => 'Selectlist for categorie identification',
    'D3_IMPORTER_MAIN_CATEGORIE_INDENTIFICATIONFIELDS_HELP'              => 'Define, which fields should unsable for categorie indentification.',
    'D3_IMPORTER_CONFIG_OVERRIDEEXTERNPICTURES'                          => 'overwrite local (/import/pictures/) with external pictures?',
    'D3_IMPORTER_CONFIG_OVERRIDEEXTERNPICTURES_HELP'                     => '<h4>Overwrite local pictures in picture import directory (/import/pictures/) with external pictures?</h4>' //
        . '<b>active:</b> If there is an external picture with the name of a local picture, the local picture will be overwritten.<br>' //
        . '<br><b>inactive:</b> If there is an external picture with the same name and size of a local picture, the name of the external picture will be appended by a unique string (filenameAppendix.extension).',
    'D3_IMPORTER_CONFIG_IMPORTTICKER_HELP'             => 'Define how many lines per run will be imported. ' //
        . 'To prevent a script abort (f.e. at a too long runtime), please choose a smaller value.',
    'D3_IMPORTER_CONFIG_IMPORTTYPE_HELP'               => 'Please select the importtype' //
        . '<ul><li>At <b>"Import and update"</b> articles will be imported and updated (standard).</li>' //
        . '<li>At <b>"Only import"</b> articles will be only imported. Existing article data are not overwritten.</li>' //
        . '<li>At <b>"Only update"</b> articles will be only overwritten. New articles are not imported.</li></ul>',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXACTIVEFROM'      => 'Active from',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXACTIVETO'        => 'Active until',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXARTNUM'          => 'Product Number',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXTITLE'           => 'Title',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXID'              => 'Internal Identno.',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSHOPID'          => 'Shop Identno.',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPARENTID'        => 'Identno. Main Product',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXACTIVE'          => 'Active',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSHORTDESC'       => 'Short Description',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXLONGDESC'        => 'Detailed Description',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPRICE'           => 'Price',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXBLFIXEDPRICE'    => 'oxblfixedprice',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPRICEA'          => 'Price A',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPRICEB'          => 'Price B',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPRICEC'          => 'Price C',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXBPRICE'          => 'Gross Price',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXTPRICE'          => 'Old Price',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXEXTURL'          => 'External URL',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUNITNAME'        => 'Unit',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUNITQUANTITY'    => 'Quantity Unit',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXURLDESC'         => 'URL Description',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXURLIMG'          => 'External URL image',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVAT'             => 'Product VAT',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXTHUMB'           => 'Preview Picture',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXICON'            => 'Icon',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_PICTURES'          => 'Product pictures',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC1'            => 'Picture1',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC2'            => 'Picture2',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC3'            => 'Picture3',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC4'            => 'Picture4',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC5'            => 'Picture5',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC6'            => 'Picture6',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC7'            => 'Picture7',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC8'            => 'Picture8',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC9'            => 'Picture9',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC10'           => 'Picture10',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC11'           => 'Picture11',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC12'           => 'Picture12',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXZOOM1'           => 'Zoom Picture 1',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXZOOM2'           => 'Zoom Picture 2',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXZOOM3'           => 'Zoom Picture 3',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXZOOM4'           => 'Zoom Picture 4',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXWEIGHT'          => 'Weight',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSTOCK'           => 'Stock Quantity',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSTOCKACTIVE'     => 'Stock Control Active',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSTOCKFLAG'       => 'Stock Flag',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXDELIVERY'        => 'Shipped on',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXINSERT'          => 'Created on',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXTIMESTAMP'       => 'Last Modification',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXLENGTH'          => 'Length',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXWIDTH'           => 'Width',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXHEIGHT'          => 'Height',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXFILE'            => 'File',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSEARCHKEYS'      => 'Search Keys',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXTEMPLATE'        => 'alt. Template',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXQUESTIONEMAIL'   => 'E-mail for question',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXISSEARCH'        => 'Is searchable',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXISCONFIGURABLE'  => 'Product is customizable',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVARNAME'         => 'Variant Name',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVARSELECT'       => 'oxvarselect',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVARMINPRICE'     => 'Minimum price of all variants',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXFOLDER'          => 'Folder',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSUBCLASS'        => 'oxsubclass',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSORT'            => 'Sorting',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSOLDAMOUNT'      => 'Quantity Sold',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXNONMATERIAL'     => 'Immaterial',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXFREESHIPPING'    => 'Free Shipping',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXREMINDACTIVE'    => 'Low stock e-mail active',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXREMINDAMOUNT'    => 'Low stock threshold',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXAMITEMID'        => 'oxamitemid',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXAMTASKID'        => 'oxamtaskid',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVENDORID'        => 'Vendor ID',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXMANUFACTURERID'  => 'Manufacturer ID',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVARCOUNT'        => 'Variant count',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSHOPINCL'        => 'Shop include',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSHOPEXCL'        => 'Shop exclude',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSHOPINCL1'       => 'Shop include',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSHOPEXCL1'       => 'Shop exclude',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXEAN'             => 'EAN',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXMPN'             => 'MPN',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXDISTEAN'         => 'Manufacturer EAN',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSTOCKTEXT'       => 'In-Stock Message',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXNOSTOCKTEXT'     => 'Out-Of-Stock Mess.',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSKIPDISCOUNTS'   => 'Skip discounts',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXRATINGCNT'       => 'Rating Count',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXRATING'          => 'Rating',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXRRVIEW'          => 'Exclusive viewable',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXRRBUY'           => 'Exclusive buyable',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXORDERINFO'       => 'Order Info',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSEOID'           => 'SEOID',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXMINDELTIME'      => 'Min. delivery time',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXMAXDELTIME'      => 'Max. delivery time',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXDELTIMEUNIT'     => 'Delivery time unit',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUPDATEPRICE'     => 'Update price',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUPDATEPRICEA'    => 'Update price A',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUPDATEPRICEB'    => 'Update price B',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUPDATEPRICEC'    => 'Update price C',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUPDATEPRICETIME' => 'Update price time',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXISDOWNLOADABLE'  => 'Is downloadable',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVPE'             => 'Packingunit',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXBUNDLEID'        => 'Bundle Identno',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVARSTOCK'        => 'Variant Stock',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVARMAXPRICE'     => 'Maximum price of all variants',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTFLAG'      => 'Importflag',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPROFILEID' => 'Importprofil-ID',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC1'      => 'Picture importfield 1',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC2'      => 'Picture importfield 2',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC3'      => 'Picture importfield 3',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC4'      => 'Picture importfield 4',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC5'      => 'Picture importfield 5',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC6'      => 'Picture importfield 6',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC7'      => 'Picture importfield 7',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC8'      => 'Picture importfield 8',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC9'      => 'Picture importfield 9',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC10'     => 'Picture importfield 10',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC11'     => 'Picture importfield 11',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC12'     => 'Picture importfield 12',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC13'     => 'Picture importfield 13',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC14'     => 'Picture importfield 14',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC15'     => 'Picture importfield 15',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC16'     => 'Picture importfield 16',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC17'     => 'Picture importfield 17',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC18'     => 'Picture importfield 18',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC19'     => 'Picture importfield 19',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC20'     => 'Picture importfield 20',
    'D3_IMPORTER_ATTRIB_LEGEND'                                          => 'legend:',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_NAME'                                => 'attributename',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_VALUE'                               => 'attributevalue at article',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_NEW_ATTRIBUTE_ASSIGN'                => 'new attribute-assignment',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_NAME_HELP'                           => 'The attributes are assigned via the titles.' //
        . '<br>The attributename can be specified language-dependent.',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_VALUE_HELP'                          => 'The "attributevalue at article" can be specified language-dependent.',
    'D3_IMPORTER_ATTRIB_DELETE_OLDSETTINGS_INFO'                         => 'The attribute-assignments of this profile are deprecated and should be updated.' //
        . '<br>It is necessary to read our <a href="https://faq.d3data.de/module/importer/anleitung-zur-umstellung-von-attributszuordnungen/" target="d3_importer_attrib"><u>FAQ article</u></a>, before you make changes!',
    'This import-profile is deprecated and should be updated.' //
    . '<br>Additional information is available in our <a href="https://faq.d3data.de/category/module/importer/" target="d3_importer_attrib"><u>FAQ</u></a>.',
    'D3_IMPORTER_ATTRIB_DELETE_OLDSETTINGS_BUTTON'                       => 'delete assignment',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_ATTRIBUTE_ASSIGN'                    => 'attribute-assigment',
    'D3IMPORTER_HELPLINK'                                                => '',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3OQM_PACKAGE'     => 'Packingunit - D³ order quantity nanager',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3OQM_MINIMUM'     => 'Minimum - D³ order quantity nanager',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3OQM_MAXIMUM'     => 'Maximum - D³ order quantity nanager',
    'D3_IMPORTER_CONFIG_OMITLINES_HELP'                => 'Quote the number of rows which should be ignored.' //
        . '<br>E.g. If the csv file contains a headline, you can enter a "1".',
    'D3_IMPORTER_CONFIG_PRICEPLUSPERCENT_HELP'         => '<strong>These option is only for the "normal" article price (oxprice)!</strong>',
    'D3_IMPORTER_CONFIG_ARTNUM2OXID_HELP'              => 'With this setting the applied article identification is used as internal shop-identifikation number (oxid).' //
        . '<br>The shop managed the unique shop-identifikation-number automatic,' //
        . ' therby this option should be used with caution.',
    'D3_IMPORTER_CONFIG_MD54OXID_HELP'                 => 'With this option a similar ident as original oxid can be created.' //
        . '<br>This option only applies with the active option "use article identifcation field as ident (data field "oxid")"',
    'D3_IMPORTER_CONFIG_PRICEDECIMALROUND_HELP'        => 'Enter a value to round the article price.' //
        . '<b>Example:</b> "2" means a rounding from 12.3456 to 12.35 or from 1.95583 to 1.96.' //
        . '<br>"1" means a rounding 12.3456 auf 12.3 or from 1.95583 to 2.' //
        . '<br><strong>These option is only for the "normal" article price (oxprice)!</strong>',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_ATTRIBUTE_ASSIGN_HELP'               => 'You can import several attributes.' //
        . '<br>Every attribute will be considered as an attribute assignment. Therefore you should only use 1 attribute for an attribute assignment.',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_LANGUAGE'                            => '[Language] active/inactive',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_LANGUAGE_HELP'                       => 'Assignments for all languages are provided.' //
        . '<br>active/<del>active</del> shows whether the language ist active in shop.',
    'D3_IMPORTER_ATTRIB_DELETE_OLDSETTINGS_QUESTION'                     => 'Do you really want to delete the deprecated assignments?',
    'D3_IMPORTER_UPDATE_OLD_ATTIBUTES_REMOVED'                           => 'With the version 4.4.1.0 the attribute-assignments has changed.' //
        . PHP_EOL . 'With the version 4.5.0.0 the old attribute-assigments are removed.' //
        . PHP_EOL . 'It is necessary to read our FAQ entry, to udnerstand the new multilangual attribute-assignments.'//
        . PHP_EOL . 'PLease follow https://faq.oxidmodule.com/Fragen-zu-speziellen-Modulen/Importer/Handbuch/Anleitung-zur-Umstellung-von-Attributszuordnungen.html !',
    'D3_IMPORTER_ATTRIB_LANGUAGE_ACTIVE'                                 => 'active',
    'D3_IMPORTER_ATTRIB_LANGUAGE_INACTIVE'                               => 'inactive',
    /* Artikel verwalten -> Kategorien -> Stamm -> Schnellsortierung */
    'GENERAL_ARTICLE_D3IMPORTFLAG'                                       => 'Importflag',
    'GENERAL_ARTICLE_D3IMPORTPROFILEID'                                  => 'Importprofil-ID',
    'GENERAL_ARTICLE_D3IMPORTPIC1'                                       => 'Picture importfield 1',
    'GENERAL_ARTICLE_D3IMPORTPIC2'                                       => 'Picture importfield 2',
    'GENERAL_ARTICLE_D3IMPORTPIC3'                                       => 'Picture importfield 3',
    'GENERAL_ARTICLE_D3IMPORTPIC4'                                       => 'Picture importfield 4',
    'GENERAL_ARTICLE_D3IMPORTPIC5'                                       => 'Picture importfield 5',
    'GENERAL_ARTICLE_D3IMPORTPIC6'                                       => 'Picture importfield 6',
    'GENERAL_ARTICLE_D3IMPORTPIC7'                                       => 'Picture importfield 7',
    'GENERAL_ARTICLE_D3IMPORTPIC8'                                       => 'Picture importfield 8',
    'GENERAL_ARTICLE_D3IMPORTPIC9'                                       => 'Picture importfield 9',
    'GENERAL_ARTICLE_D3IMPORTPIC10'                                      => 'Picture importfield 10',
    'GENERAL_ARTICLE_D3IMPORTPIC11'                                      => 'Picture importfield 11',
    'GENERAL_ARTICLE_D3IMPORTPIC12'                                      => 'Picture importfield 12',
    'GENERAL_ARTICLE_D3IMPORTPIC13'                                      => 'Picture importfield 13',
    'GENERAL_ARTICLE_D3IMPORTPIC14'                                      => 'Picture importfield 14',
    'GENERAL_ARTICLE_D3IMPORTPIC15'                                      => 'Picture importfield 15',
    'GENERAL_ARTICLE_D3IMPORTPIC16'                                      => 'Picture importfield 16',
    'GENERAL_ARTICLE_D3IMPORTPIC17'                                      => 'Picture importfield 17',
    'GENERAL_ARTICLE_D3IMPORTPIC18'                                      => 'Picture importfield 18',
    'GENERAL_ARTICLE_D3IMPORTPIC19'                                      => 'Picture importfield 19',
    'GENERAL_ARTICLE_D3IMPORTPIC20'                                      => 'Picture importfield 20',
    'D3_IMPORTER_IMPORT_TESTLICENCE_NOTICE'                              => 'The module is licensed as a trialversion.<br>Currently, the amount of importable articles/pictures and profiles is limited.',
    'd3mxdesc'                                                           => 'articlefields',
    'd3_d3importer_controllers_admin_desc_itemmain'                      => 'edit articlefield',
    'D3_D3IMPORTERDESC_MENUSUBITEM'                                      => 'edit articlefield',
    'D3IMPORTERDESC_NEW'                                                 => 'new articlefield',
    'D3IMPORTERDESC_OXISDISABLED'                                        => 'active',
    'HELP_D3IMPORTERDESC_OXISDISABLED'                                   => 'de/activate the articlefield for the interface of the Importer',
    'D3IMPORTERDESC_OXFIELD'                                             => 'databasefieldname',
    'HELP_D3IMPORTERDESC_OXFIELD'                                        => 'Set the fieldname of the databasefield from oxarticles or oxartextends. F.e. oxtitle, oxthumb...',
    'D3IMPORTERDESC_OXDESC'                                              => 'fieldname language 1',
    'HELP_D3IMPORTERDESC_OXDESC'                                         => 'Set an userfriendly fieldname for the articlefield in language 1.',
    'D3IMPORTERDESC_OXDESC_1'                                            => 'fieldname language 2',
    'HELP_D3IMPORTERDESC_OXDESC_1'                                       => 'Set an userfriendly fieldname for the articlefield in language 2.',
    'D3IMPORTERDESC_OXORDER'                                             => 'sort',
    'HELP_D3IMPORTERDESC_OXORDER'                                        => 'set the sorting of the fields in the importer adminstration.<br>' //
        . 'Often used articlefields can be placed in the top with a low number.',
    'D3IMPORTERDESC_OXISPIC'                                             => 'Pic',
    'HELP_D3IMPORTERDESC_OXISPIC'                                        => 'de/activate the articlefield for the importer administration of the picture import (new field will not shown in picture import yet).',
    'HELP_D3IMPORTERDESC'                                                => 'You can administrate the article fields for the importer.<br>'//
        . 'These articlefields are used in serveral parts of the importer module (article import/article fields, settings/article identification). <br>'//
        . 'With this, you can add or reduce the article fields in importer administration.',
    'D3_IMPORTER_PRICE2ART_PERCENTOPTION'                                => 'is % discount price?',
    'HELP_D3_IMPORTER_PRICE2ART_PERCENTOPTION'                           => 'If this checkbox active, the price will be imported as an percentual price. You will find more Info\'s under /Administer Products/Products/Stock/Scale Prices/.',
    'HELP_D3_IMPORTER_PRICE2ART_PRICE'                                   => 'Set the price for the scale (comma\'s will be replaced by a point, please avoid entries like: 1,234.56<br> better solution: 1234,56 or 1234.56).<br><br>To import percentage scale price\'s, please use the % sign. f.e.: 10% or 1,23% or 1.23%',
    'D3_PICTURE_IMPORT_LOAD_PROFILE'                                     => 'Please choose an importprofile.',
    'HELP_D3_PICTURE_EXTPICTURE_START'                                   => 'check the box, if the pictures to be imported are located in external URL\'s.<br>For example: https://placeimg.com/1000/1000/any.jpg.' //
        . '<br><br>The picture import calls the URL\'s and download the pictures into the defined picture import folder.',
    'D3_IMPORTER_PICTURE_IMPORT_STEP1'                                   => 'step 1:',
    'D3_IMPORTER_PICTURE_IMPORT_STEP2'                                   => 'step 2:',
    'D3_IMPORTER_FIELDS_CHECKALL'                                        => 'de/select all update checkboxes',
    'D3_IMPORTER_CONFIG_BLDELETEMASTERPICTURE'                           => 'This option (active) deletes master images before importing (recommended)',
    'D3_IMPORTER_CONFIG_BLDELETEMASTERPICTURE_HELP'                      => 'Check this option to prevent unused pictures on your server.<br>'.PHP_EOL
        .'During the import, previous article-pictures will be deleted through the shop.<br>'.PHP_EOL
        .'The deletion includes the article-related pictures in folders "/master/" and the generated pictures in "/generated/".<br>'.PHP_EOL
        .'<br>'.PHP_EOL
        .'Uncheck this option to import the images directly.<br>'.PHP_EOL
        .'Unused image files may be created in the /master/product/*/ directories.',
    'D3_IMPORTER_CONFIG_PATHTOMOVE'                                      => 'action after import the picture:',
    'D3_IMPORTER_CONFIG_PATHTOMOVE_HELP'                                 => 'Choose a option to delete or move the picture from {shoproot}/source/import/pictures/.<br>'
        .'The folder requires an absolute path, f.e.: /var/www/myshop.de/{FolderName}/',
    'D3_IMPORTER_CONFIG_PICTURESACTIONAFTERIMPORT_DELETE'                => 'delete picture',
    'D3_IMPORTER_CONFIG_PICTURESACTIONAFTERIMPORT_MOVE'                  => 'move picture into folder',
    'D3_IMPORTER_CONFIG_FOLDER'                                          => 'absolute path to target directory',
    'D3_IMPORTER_CONFIG_FOLDER_HELP'                                     => 'Enter the absolute path of the target directory here. Make sure that the destination directory is present and writable.',

    'D3_IMPORTER_SETUP_CREATEDIRECTORY'                                  => 'Create the directory "%s".',
);
