<?php
/**
 * This Software is the property of Data Development and is protected
 * by copyright law - it is NOT Freeware.
 * Any unauthorized use of this software without a valid license
 * is a violation of the license agreement and will be prosecuted by
 * civil and criminal law.
 * https://www.shopmodule.com
 *
 * @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
 * @author        D3 Data Development <support@shopmodule.com>
 * @link          https://www.oxidmodule.com
 */

$sLangName = "Deutsch";
$iLangNr   = 0;
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(

    //Tabs

    //Navigation
    'charset'                                                            => 'ISO-8859-15',
    'd3mximporter'                                                       => '<i class="fas fa-fw fa-database"></i> Importer',
    'd3mxarticleimport'                                                  => 'Artikelimport',
    'd3mximporter_cfg'                                                   => 'Einstellungen',
    'd3mximporter_cfg_main'                                              => 'Stamm',
    'd3tbclimporter_cfg_main'                                            => 'Grundeinstellungen',
    'd3tbclimporter_main'                                                => 'Stamm',
    'd3tbclimporter_fields'                                              => 'Artikelfelder',
    'd3tbclimporter_category'                                            => 'Kategorien',
    'd3tbclimporter_cross'                                               => 'Cross-Selling',
    'd3tbclimporter_attrib'                                              => 'Attribute',
    'd3tbclimporter_selectlist'                                          => 'Auswahllisten',
    'd3tbclimporter_variants'                                            => 'Varianten',
    'd3tbclimporter_price2art'                                           => 'Staffelpr.',
    'd3tbclimporter_vendors'                                             => 'Hersteller',
    'd3tbclimporter_config'                                              => 'Konfig.',
    'd3tbclimporter_mall'                                                => 'Mall',
    'd3tbclimporter_import'                                              => 'Import',
    'd3tbclimporter_afterimport'                                         => 'Nach Import',
    'd3mxpictureimport'                                                  => 'Bilderimport',
    'd3tbclpicture_main'                                                 => 'Stamm',
    'd3tbclpicture_import'                                               => 'Import',
    'D3_IMPORTER_METADATA_ALTITLE'                                       => 'D³ Importer',
    'D3_IMPORTER_METADATA_ALDESC'                                        => 'Umfangreiche Importmöglichkeiten der Artikel inkl. dem Import von Bildern, sowie alle Datenfelder von oxarticles, Kategorien, Cross-Selling, Attribute, Auswahllisten, Varianten, Staffelpreise, Hersteller/Lieferanten',
    'D3_IMPORTER_METADATA_AUTHOR'                                        => 'D³ Data Development, Inh. Thomas Dartsch',
    'D3_TOOLTIPS_NEWIMPORTPROFIL'                                        => 'Neues Importprofil anlegen',
    'D3_IMPORTER_CFG_LIST_SETTLANG'                                      => 'Einstellungen für Sprache',
    'D3_IMPORTER_CFG_MAIN_TITLE'                                         => 'Importer - Einstellungen',
    'D3_IMPORTER_MENUITEM'                                               => 'Importer',
    'D3_IMPORTER_ROW'                                                    => 'Zeile',
    'D3_IMPORTER_ROW_OF'                                                 => 'von',
    'D3_IMPORTER_LIST_MENUSUBITEM'                                       => 'Artikelimport',
    'D3_PICTURE_LIST_MENUSUBITEM'                                        => 'Bildimport',
    'D3_IMPORTER_MAIN_OXID'                                              => 'Profil-ID',
    'D3_IMPORTER_MAIN_DESCRIPTION'                                       => 'Profilname',
    'D3_IMPORTER_MAIN_IMPORTFILE'                                        => 'Importdatei',
    'D3_IMPORTER_MAIN_NOFILE'                                            => '-- keine --',
    'D3_IMPORTER_MAIN_NEWFILE'                                           => 'neue Datei hochladen (max. Größe: %1$s)',
    'D3_IMPORTER_MAIN_ALLOWEXT_MAXFILESIZE_HELP'                         => 'Erlaubte Dateitypen sind "csv" oder "txt".',
    'D3_IMPORTER_MAIN_EXCEEDS_MAXFILESIZE'                               => '"${filename}" übersteigt die maximale Dateigröße von ${maxfilesize}.',
    'D3_IMPORTER_MAIN_COLSEP'                                            => 'Datei-Spaltentrennung',
    'D3_IMPORTER_MALL_COLUMSEPARATOR_MALL_HELP'                          => 'z.B. , ; oder TAB (TAB = Tabulator)',
    'D3_IMPORTER_MAIN_TEXTSEP'                                           => 'Texttrenner (optional)',
    'D3_IMPORTER_MAIN_TEXTSEPDESCRIPTION_HELP'                           => 'z.B. \' oder "',
    'D3_IMPORTER_MAIN_FIFELINFO_HEAD'                                    => 'Datei-Info',
    'D3_IMPORTER_MAIN_FIFELINFO_NAME'                                    => 'Name',
    'D3_IMPORTER_MAIN_FIFELINFO_SIZE'                                    => 'Größe',
    'D3_IMPORTER_MAIN_FIFELINFO_CHANGE'                                  => 'letzte Änderung',
    'D3_IMPORTER_MAIN_FIFELINFO_READ'                                    => 'lesbar',
    'D3_IMPORTER_MAIN_FIFELINFO_WRITE'                                   => 'beschreibbar',
    'D3_IMPORTER_MAIN_FIFELINFO_CSV'                                     => 'CSV',
    'D3_IMPORTER_MAIN_FIFELINFO_ROWS'                                    => 'Zeilen',
    'D3_IMPORTER_MAIN_FIFELINFO_COLUMS'                                  => 'Spalten',
    'D3_IMPORTER_MAIN_FIFELINFO_RIGHTS'                                  => 'Linux-Rechte',
    'D3_IMPORTER_MAIN_FIFELINFO_OWNER'                                   => 'Besitzer',
    'D3_IMPORTER_MAIN_FIFELINFO_GROUP'                                   => 'Gruppe',
    'D3_IMPORTER_FIELDS_COLUM'                                           => 'Spalte',
    'D3_IMPORTER_FIELDS_COLUMASSIGN'                                     => 'Spalteninhalt und Zuordnung',
    'D3_IMPORTER_FIELDS_UPDATE'                                          => 'Update',
    'D3_IMPORTER_FIELDS_INFOTEXT_HELP'                                   => 'Soll eine Spalte auch für das Artikelupdate verwendet werden, markieren Sie die dazugehörige Checkbox "Update". <br>',
    'D3_IMPORTER_FIELDS_XXXX'                                            => 'Hinweis:  <b>Pflicht ist die Zuordnung der Artikelidentifikation!</b>',
    'D3_IMPORTER_FIELDS_XXXX_HELP'                                       => 'Sie können die Artikelidentifikation im Tab "Konfig." einstellen.<br> Die Artikelidentifikation muss im Tab "Artikelfelder" ebenfalls ausgewählt sein.<br><br>Bspw.: oxartnum (Artikelnummer)',
    'D3_IMPORTER_CATEGORY_ASSIGN'                                        => 'Kategoriefeld Zuordung',
    'D3_IMPORTER_CATEGORY_NOASSIGN'                                      => '-- keine --',
    'D3_IMPORTER_CATEGORY_ASSIGNINFO_HELP'                               => '<b>Pflichtfeld!</b> Legen Sie hier fest, auf welches Feld als Referenz geprüft werden soll.<br><br>Hinweis: Nur bei "Titel (oxtitle)" wird im Importvorgang die Kategoriestruktur angelegt, sofern diese nicht vorhanden ist.',
    'D3_IMPORTER_CATEGORY_ASSIGN_NEEDED'                                 => '<b>Pflichtfeld!</b>',
    'D3_IMPORTER_CATEGORY_IMPORTTYPE'                                    => 'Importtyp',
    'D3_IMPORTER_CATEGORY_IMPORTTYPE1'                                   => 'Nur Import',
    'D3_IMPORTER_CATEGORY_IMPORTTYPE2'                                   => 'Artikel-Kat.-Zuordnungen vorher löschen',
    'D3_IMPORTER_CATEGORY_IMPORTTYPEINFO_HELP'                           => '"Import" = Die Kategorien werden normal importiert bzw. dem Artikel zugeordnet<br>"vorher löschen" = Alle Kategoriezuordnungen des aktuellen Artikels werden vor dem Update gelöscht.',
    'D3_IMPORTER_CATEGORY_IMPORTCOLUM'                                   => 'Spaltenzuordnung',
    'D3_IMPORTER_CATEGORY_COLSEP'                                        => 'interne Spaltentrennung',
    'D3_IMPORTER_CATEGORY_IMPORTCOLUMINFO_HELP'                          => 'Ordnet die Kategoriedaten aus dieser Importspalte dem aktuellen Artikel zu.',
    'D3_IMPORTER_CROSS_IMPORTTYPE'                                       => 'Cross-Selling Importtyp',
    'D3_IMPORTER_CROSS_IMPORTTYPE1'                                      => 'Nur Import',
    'D3_IMPORTER_CROSS_IMPORTTYPE2'                                      => 'Artikel-Cross-Sell.-Zuordnungen vorher löschen',
    'D3_IMPORTER_CROSS_IMPORTTYPEINFO_HELP'                              => '"Nur Import" = Das Cross-Selling wird normal dem Artikel zugeordnet<br>"vorher löschen" = Alle Cross-Selling-Zuordnungen des aktuellen Artikels werden vor dem Update gelöscht.',
    'D3_IMPORTER_CROSS_NOASSIGN'                                         => '-- keine --',
    'D3_IMPORTER_CROSS_IMPORTCOLUM'                                      => 'Spaltenzuordnung',
    'D3_IMPORTER_CROSS_IMPORTCOLUMINFO_HELP'                             => 'Ordnet die Dateispalte mit den Crosselling-Daten zu',
    'D3_IMPORTER_CROSS_COLSEP'                                           => 'interne Spaltentrennung',
    'D3_IMPORTER_MALL_IMPORTCOLUM_MALL'                                  => 'Spaltenzuordnung',
    'D3_IMPORTER_MALL_IMPORTCOLUM_MALL_HELP'                             => 'Ordnet die Dateispalte mit den Shopidents zu',
    'D3_IMPORTER_MALL_COLUMSEPARATOR_MALL'                               => 'interne Spaltentrennung',
    'D3_IMPORTER_ACC_IMPORTTYPE'                                         => 'Zubehör Importtyp',
    'D3_IMPORTER_ACC_IMPORTTYPE1'                                        => 'Nur Import',
    'D3_IMPORTER_ACC_IMPORTTYPE2'                                        => 'Artikel-Zubehör-Zuordnungen vorher löschen',
    'D3_IMPORTER_ACC_IMPORTTYPEINFO_HELP'                                => '"Nur Import" = Das Zubehör wird normal dem Artikel zugeordnet<br>"vorher löschen" = Alle Zubehör-Zuordnungen des aktuellen Artikels werden zuvor gelöscht.',
    'D3_IMPORTER_ACC_NOASSIGN'                                           => '-- keine --',
    'D3_IMPORTER_ACC_IMPORTCOLUM'                                        => 'Spaltenzuordnung',
    'D3_IMPORTER_ACC_IMPORTCOLUMINFO_HELP'                               => 'Ordnet die Dateispalte mit den Zubehör-Daten zu',
    'D3_IMPORTER_ACC_COLSEP'                                             => 'interne Spaltentrennung',
    'D3_IMPORTER_ATTRIB_IMPORTTYPE'                                      => 'Attribute Importtyp',
    'D3_IMPORTER_ATTRIB_IMPORTTYPE1'                                     => 'Nur Import',
    'D3_IMPORTER_ATTRIB_IMPORTTYPE2'                                     => 'Artikel-Attribut-Zuordnungen vorher löschen',
    'D3_IMPORTER_ATTRIB_IMPORTTYPEINFO_HELP'                             => '"Nur Import" = Die Attribute werden normal dem Artikel zugeordnet<br>"vorher löschen" = Alle Attribut-Zuordnungen des aktuellen Artikels werden vor dem Update gelöscht.',
    'D3_IMPORTER_ATTRIB_NOASSIGN'                                        => '-- keine --',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM'                                     => 'Spaltenzuordnung',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUMINFO_HELP'                            => 'Ordnet die Dateispalte mit den Attributsdaten zu',
    'D3_IMPORTER_ATTRIB_COLSEP1'                                         => 'Attributstrennung',
    'D3_IMPORTER_ATTRIB_COLSEPDESCRIPTION1_HELP'                         => 'Geben Sie hier ein Trennzeichen an, wenn in der Spalte mehrere Attribute hinterlegt sind. (z.B. "Material|Oberfläche|...") dann "|"',
    'D3_IMPORTER_ATTRIB_COLSEP2'                                         => 'Werttrennung',
    'D3_IMPORTER_ATTRIB_COLSEPDESCRIPTION2_HELP'                         => 'Geben Sie hier ein Trennzeichen an, wenn in der Spalte zusätzlich die Attributswerte hinterlegt sind. (z.B. "Material,Aluminium|Oberfläche,matt|...") dann ","',
    'D3_IMPORTER_SELECTLIST_IMPORTTYPE'                                  => 'Auswahllisten Importtyp',
    'D3_IMPORTER_SELECTLIST_IMPORTTYPE1'                                 => 'Nur Import',
    'D3_IMPORTER_SELECTLIST_IMPORTTYPE2'                                 => 'Alle Auswahllisten vorher löschen',
    'D3_IMPORTER_SELECTLIST_IMPORTTYPEINFO_HELP'                         => '"Nur Import" = Eine neue Auswahlliste wird erstellt und dem Artikel zugeordnet.<br>"Alle Auswahllisten vorher löschen" = Alle Auswahllisten, die ausschließlich dem aktuellen Artikels zugeordnet sind, werden vor dem Update gelöscht.',
    'D3_IMPORTER_SELECTLIST_NOASSIGN'                                    => '-- keine --',
    'D3_IMPORTER_SELECTLIST_NAME'                                        => 'Titel der Auswahlliste',
    'D3_IMPORTER_SELECTLIST_ALTNAME'                                     => 'Alternativtitel',
    'D3_IMPORTER_SELECTLIST_VALUE'                                       => 'Auswahlfelder',
    'D3_IMPORTER_SELECTLIST_SEPARATOR'                                   => 'Werttrenner',
    'D3_IMPORTER_SELECTLIST_PRICESEPARATOR'                              => 'Preistrenner',
    'D3_IMPORTER_SELECTLIST_TITLE_HELP'                                  => 'Geben Sie hier das CSV-Importfeld an, in dem der Titel z.B. "Farbe" hinterlegt ist.',
    'D3_IMPORTER_SELECTLIST_ALTTITLE_HELP'                               => 'Ist kein Feld für "Titel der Auswahlliste" vorhanden, oder ist der Inhalt teilweise leer, so kann hier ein Alternativtitel z.B. "Auswahl" angegeben werden.',
    'D3_IMPORTER_SELECTLIST_SELECTFIELDS_HELP'                           => 'CSV-Importfeld mit den Werten der Auswahlliste',
    'D3_IMPORTER_SELECTLIST_SEPARATOR_HELP'                              => 'Stehen mehrere Werte im CSV-Importfeld "Auswahlfelder", so muss der verwendete Trenner angegeben werden. z.B. "@" wenn in der CSV "rot@gelb@grün..." steht.',
    'D3_IMPORTER_SELECTLIST_PRICESEPARATOR_HELP'                         => 'Zusätzlich können auch Preisänderungen (fest und in %) mit importiert werden. z.B. "rot|2,34@gelb|5%@grün|1,23...". In dem Beispiel wird als Werttrenner "@" und als Preistrenner "|" eingetragen.',
    'D3_IMPORTER_SELECTLIST_INFOTEXT'                                    => 'Es können beliebig viele Auswahllisten, mit beliebig viele Werten pro Artikel importiert werden.',
    'D3_IMPORTER_VARIANTS_IMPORTTYPE'                                    => 'Varianten Importtyp',
    'D3_IMPORTER_VARIANTS_IMPORTTYPE1'                                   => 'Nur Import',
    'D3_IMPORTER_VARIANTS_IMPORTTYPE2'                                   => 'Varianten vorher löschen',
    'D3_IMPORTER_VARIANTS_IMPORTTYPEINFO'                                => '"Nur Import" = Die Varianten werden dem Vaterartikel neu zugeordnet oder aktualisiert<br>"vorher löschen" = Alle Varianten-Artikel des aktuellen Vater-Artikels werden vor dem Update gelöscht.',
    'D3_IMPORTER_VARIANTS_NOASSIGN'                                      => '-- keine --',
    'D3_IMPORTER_VARIANTS_IMPORTCOLUM'                                   => 'Variantenerkennung',
    'D3_IMPORTER_VARIANTS_IMPORTCOLUMINFO'                               => 'Ordnet die Dateispalte mit der Artikelidentifikation (z.B. ArtNr oder EAN) des Vater-Artikels zu.',
    'D3_IMPORTER_PRICE2ART_IMPORTTYPE'                                   => 'Importtyp',
    'D3_IMPORTER_PRICE2ART_IMPORTTYPE1'                                  => 'Nur Import',
    'D3_IMPORTER_PRICE2ART_IMPORTTYPE2'                                  => 'Staffelpreise vorher löschen',
    'D3_IMPORTER_PRICE2ART_IMPORTTYPEINFO_HELP'                          => '"Nur Import" = Die Staffelpreise werden dem Artikel neu zugeordnet oder aktualisiert.<br>"vorher löschen" = Alle Staffelpreise des Artikels werden vor dem Update gelöscht.',
    'D3_IMPORTER_PRICE2ART_PRICE'                                        => 'Staffelpreis',
    'D3_IMPORTER_PRICE2ART_AMOUNTFROM'                                   => 'Menge von',
    'D3_IMPORTER_PRICE2ART_AMOUNTTO'                                     => 'Menge bis',
    'D3_IMPORTER_VENDORS_IMPORTTYPE'                                     => 'Lieferanten erstellen',
    'D3_IMPORTER_VENDORS_IMPORTTYPE1'                                    => 'Ja',
    'D3_IMPORTER_VENDORS_IMPORTTYPE2'                                    => 'Nein, nur Zuordnung',
    'D3_IMPORTER_VENDORS_IMPORTTYPEINFO_HELP'                            => '"Ja" = Existiert der Lieferant nicht bereits im Shop, wird er neu angelegt und dem Artikel zugeordnet.<br>"nur Zuordnung" = Der Artikel wird nur einem existierenden Lieferanten zugeordnet.',
    'D3_IMPORTER_VENDORS_ASSIGN'                                         => 'Lieferant Importspalte',
    'D3_IMPORTER_VENDORS_NOASSIGN'                                       => '-- keine --',
    'D3_IMPORTER_VENDORS_ASSIGNINFO_HELP'                                => 'Ordnet die Dateispalte mit dem Lieferantennamen zu.',
    'D3_IMPORTER_MANUFACTURER_IMPORTTYPE'                                => 'Hersteller erstellen',
    'D3_IMPORTER_MANUFACTURER_IMPORTTYPE1'                               => 'Ja',
    'D3_IMPORTER_MANUFACTURER_IMPORTTYPE2'                               => 'Nein, nur Zuordnung',
    'D3_IMPORTER_MANUFACTURER_IMPORTTYPEINFO_HELP'                       => '"Ja" = Existiert der Hersteller nicht bereits im Shop, wird er neu angelegt und dem Artikel zugeordnet.<br>"nur Zuordnung" = Der Artikel wird nur einem existierenden Hersteller zugeordnet.',
    'D3_IMPORTER_MANUFACTURER_ASSIGN'                                    => 'Hersteller Importspalte',
    'D3_IMPORTER_MANUFACTURER_NOASSIGN'                                  => '-- keine --',
    'D3_IMPORTER_MANUFACTURER_ASSIGNINFO_HELP'                           => 'Ordnet die Dateispalte mit dem Herstellernamen zu.',
    'D3_IMPORTER_CONFIG_MAINOPTIONS'                                     => 'Grundeinstellungen',
    'D3_IMPORTER_MALL_MAINOPTIONS'                                       => 'Einstellungen',
    'D3_IMPORTER_CONFIG_IMPORTTICKER'                  => 'Dateizeilen pro Durchlauf',
    'D3_IMPORTER_CONFIG_IMPORTTYPE'                    => 'Importtyp',
    'D3_IMPORTER_CONFIG_IMPORTTYPE_STANDARD'           => 'Import und Update',
    'D3_IMPORTER_CONFIG_IMPORTTYPE_IMPORT'             => 'nur Import',
    'D3_IMPORTER_CONFIG_IMPORTTYPE_UPDATE'             => 'nur Update',
    'D3_IMPORTER_CONFIG_OMITLINES'                     => 'Anzahl Datei-Kopfzeilen (werden nicht importiert)',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT'                   => 'Artikelidentifikation',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_HELP'              => 'Legen Sie hier eine <b>eindeutige</b> Artikelidentifikation fest,' //
        . ' so dass keine Dubletten vorkommen.<br>Das gewählte Feld muß zwingend unter "Artikelfelder" einer Importspalte zugeordnet werden.' //
        . '<br>Standard ist die Artikelnummer.' //
        . '<br>Die Felder können Sie unter "Importer/Einstellungen/Grundeinstellungen/Einstellungen/Auswahl für Artikelidentifikationsfelder" hinzufügen.',
    'D3_IMPORTER_CONFIG_PRICEOPTIONS'                                    => 'Preis Optionen',
    'D3_IMPORTER_CONFIG_PRICEPLUSPERCENT'              => 'Importierten Artikelpreis um x % erhöhen.',
    'D3_IMPORTER_CONFIG_PRICEDECIMALROUND'             => 'Importierten Artikelpreis auf x Nachkommastellen runden.',
    'D3_IMPORTER_CONFIG_IDENTOPTIONS'                                    => 'Artikel-Ident Optionen (Expertenmodus)',
    'D3_IMPORTER_CONFIG_ARTNUM2OXID'                   => 'Artikelidentifikationsfeld als Ident (Datenfeld &quot;oxid&quot;) nutzen',
    'D3_IMPORTER_CONFIG_MD54OXID'                      => 'Zusätzlich das Identfeld mit MD5 codieren',
    'D3_IMPORTER_IMPORT_START'                                           => 'Artikelimport starten!',
    'D3_IMPORTER_IMPORT_INFO1'                                           => 'Importierte Zeilen',
    'D3_IMPORTER_IMPORT_INFO2'                                           => 'von',
    'D3_IMPORTER_IMPORT_IMPORTEND'                                       => 'Import beendet.',
    'D3_IMPORTER_IMPORT_STATISTICHEAD'                                   => 'Ergebnis (inkl. Varianten):',
    'D3_IMPORTER_IMPORT_STATISTIC1'                                      => 'Importierte Artikel:',
    'D3_IMPORTER_IMPORT_STATISTIC2'                                      => 'Aktualisierte Artikel:',
    'D3_IMPORTER_AFTERIMPORT_PREINFO0'                                   => 'Artikel wurden mit diesem Profil in der Vergangenheit bearbeitet.',
    'D3_IMPORTER_AFTERIMPORT_PREINFO1'                                   => 'Artikel',
    'D3_IMPORTER_AFTERIMPORT_PREINFO2'                                   => 'wurden davon bei Ihrem letzten Import nicht importiert oder aktualisiert.',
    'D3_IMPORTER_AFTERIMPORT_PREINFO3'                                   => 'Sie können diese Artikel jetzt deaktivieren oder komplett löschen lassen.',
    'D3_IMPORTER_AFTERIMPORT_TICKER'                                     => 'Artikel pro Durchlauf',
    'D3_IMPORTER_AFTERIMPORT_MAINARTICLE'                                => 'Hauptartikel',
    'D3_IMPORTER_AFTERIMPORT_VARIANTS'                                   => 'Varianten',
    'D3_IMPORTER_AFTERIMPORT_DOINACTIVE'                                 => 'Alle Artikel deaktivieren',
    'D3_IMPORTER_AFTERIMPORT_DODELETE'                                   => 'Alle Artikel löschen',
    'D3_IMPORTER_AFTERIMPORT_INFO1'                                      => 'Bearbeitete Artikel',
    'D3_IMPORTER_AFTERIMPORT_INFO2'                                      => 'von',
    'D3_IMPORTER_AFTERIMPORT_IMPORTEND'                                  => 'Nach-Import beendet.',
    'D3_IMPORTER_FAILUPLOAD_10'                                          => 'Fehler: Datei fehlerhaft, leer oder unvollständig hochgeladen.',
    'D3_IMPORTER_FAILUPLOAD_11'                                          => 'Fehler: Nicht erlaubte Dateiendung.',
    'D3_IMPORTER_FAILUPLOAD_12'                                          => 'Fehler: Das Zielverzeichnis wurde im Shop nicht gefunden.',
    'D3_IMPORTER_FAILUPLOAD_13'                                          => 'Fehler: Die Datei konnte nicht im Zielverzeichnis gespeichert werden. (ungenügende Schreibrechte?)',
    'D3_IMPORTER_FAILUPLOAD_20'                                          => 'Fehler: Kein Lizenzschlüssel oder Modul inaktiv.',
    'D3_IMPORTER_FAILCONFIG_10'                                          => 'Fehler: Kein Profil geladen!',
    'D3_IMPORTER_FAILCONFIG_11'                                          => 'Fehler: Keine Importdatei gewählt!',
    'D3_IMPORTER_FAILCONFIG_12'                                          => 'Fehler: Importdatei fehlerhaft oder leer!',
    'D3_IMPORTER_FAILCONFIG_13'                                          => 'Fehler: Kein Separator gesetzt!',
    'D3_IMPORTER_FAILCONFIG_14'                                          => 'Fehler: Importdatei fehlerhaft oder leer!',
    'D3_IMPORTER_FAILCONFIG_15'                                          => 'Fehler: Keine "Nach-Import" Aktion definiert.',
    'D3_IMPORTER_FAILCONFIG_20'                                          => 'Fehler: Kein Lizenzschlüssel oder Modul inaktiv.',
    'D3_IMPORTER_FAILIMPORT_10'                                          => 'Fehler: Die Importdatei konnte nicht geladen werden!',
    'D3_IMPORTER_FAILIMPORT_11'                                          => 'Fehler: Das Feld für die Artikelidentifikation wurde im Reiter "Artikelfelder" oder "Konfig." nicht zugeordnet!',
    'D3_IMPORTER_FAILIMPORT_12'                                          => 'Fehler: Keine oder ungültige "Nach-Import" Aktion definiert.',
    'D3_IMPORTER_FAILIMPORT_20'                                          => 'Fehler: Kein Lizenzschlüssel oder Modul inaktiv.',
    'D3_PICTURE_IMPORTFIELD'                                             => 'Importiere',
    'D3_PICTURE_IMPORTFIELD_OXPIC'                                       => 'Bild',
    'D3_PICTURE_IMPORTFIELD_OXZOOM'                                      => 'Zoom',
    'D3_PICTURE_NOASSIGN'                                                => '-- keines --',
    'D3_PICTURE_FAILCONFIG_10'                                           => 'Fehler: Kein Profil geladen!',
    'D3_PICTURE_FAILCONFIG_11'                                           => 'Fehler: Das Bilder-Importverzeichnis wurde nicht gefunden!',
    'D3_PICTURE_FAILCONFIG_12'                                           => 'Fehler: Das Bilder-Importverzeichnis konnte nicht eingelesen werden!',
    'D3_PICTURE_FAILCONFIG_13'                                           => 'Fehler: Keine Dateien im Bilder-Importverzeichnis gefunden.',
    'D3_PICTURE_FAILCONFIG_14'                                           => 'Fehler: Importdatei fehlerhaft oder leer!',
    'D3_PICTURE_FAILCONFIG_20'                                           => 'Es wurden keine externen Bild-Urls in den Importfeldern der Artikeltabelle gefunden.<br>Dies ist kein Fehler, wenn Sie keine Bilder aus einer externen Quelle importieren wollen oder dies bereits vollständig getan haben.',
    'D3_PICTURE_FAILCONFIG_30'                                           => 'Fehler: Kein Lizenzschlüssel oder Modul inaktiv.',
    'D3_PICTURE_IMPORT_INFO_1'                                           => 'Verzeichnis-Info:',
    'D3_PICTURE_IMPORT_INFO_2'                                           => 'Bilddateien:',
    'D3_PICTURE_IMPORT_INFO_3'                                           => 'Bereits bearbeitet:',
    'D3_PICTURE_IMPORT_INFO_4'                                           => 'Davon importiert:',
    'D3_PICTURE_IMPORT_NOTICE_1'                                         => 'Hinweis:<br>Es wurden keine Bilddateien im Bildimport-Verzeichnis gefunden.<br> Sie müssen zuerst das Bildverzechnis neu einlesen, um danach einen Bildimport vornehmen zu können.',
    'D3_PICTURE_IMPORT_NOTICE_2'                                         => 'Hinweis:<br>Alle zuvor eingelesenen Bilddateien wurden bereits bei einem früheren Bildimport bearbeitet.<br>Wenn Sie einen neuen Bildimport starten möchten,<br> so müssen Sie zuerst das Bildimport-Verzeichnis neu einlesen lassen.',
    'D3_PICTURE_IMPORT_NOTICE_3'                                         => 'Hinweis:<br>Es wurden bereits Bilder bearbeitet.<br> Sie können jetzt den Bildimport mit den restlichen noch zu bearbeitenden Bildern fortführen.<br>Oder Sie lesen das Bildverzeichnis erneut ein.<br> In dem Fall wird allerdings erneut versucht, alle gefundenen Bilder zu importieren.',
    'D3_PICTURE_IMPORT_NOTICE_4'                                         => 'Hinweis:<br>Sollten Sie neue Bilder ins Bildimport-Verzeichnis kopiert haben,<br>so lesen Sie das Verzeichnis erneut ein, um die Bildanzahl zu aktualisieren.',
    'D3_PICTURE_SCANDIR_START'                                           => 'Bildimportverzeichnis einlesen',
    'D3_PICTURE_EXTPICTURE_START'                                        => 'Externe Bilder einlesen',
    'D3_PICTURE_IMPORT_START'                                            => 'Bildimport starten!',
    'D3_PICTURE_IMPORT_INFO1'                                            => 'Bearbeitete Bilder',
    'D3_PICTURE_IMPORT_INFO2'                                            => 'von',
    'D3_PICTURE_IMPORT_INFO3'                                            => 'Davon importierte Bilder',
    'D3_PICTURE_IMPORT_IMPORTEND'                                        => 'Bildimport beendet.',
    'D3_PICTURE_EXTIMPORT_INFO1'                                         => 'Bearbeitete externe Bild-Urls',
    'D3_PICTURE_EXTIMPORT_IMPORTEND'                                     => 'Externer Bildimport beendet. Der eigentliche Bildimport kann nun gestartet werden.',
    'D3_PICTURE_IMPORT_ERRORPRETEXT'                                     => 'Fehler bei:',
    'D3_PICTURE_IMPORT_ERRORTYPE_10'                                     => 'Keine gültige Bild-Url',
    'D3_PICTURE_IMPORT_ERRORTYPE_20'                                     => 'curl Verbindungsfehler',
    'D3_PICTURE_IMPORT_ERRORTYPE_30'                                     => 'Kein gültiger Dateiname',
    'D3_PICTURE_IMPORT_ERRORTYPE_40'                                     => 'Kein gültige Bildtyp',
    'D3_IMPORTER_PICTURE_CHOOSE_PROFILE'                                 => 'Bitte wählen Sie ein Importprofil aus.',
    'D3_IMPORTER_EXPORTCONFIG'                                           => 'Importprofil exportieren',
    /* Grundeinstellungen */
    'D3_IMPORTER_MAIN_MAINSETTINGS'                                      => 'Einstellungen',
    'D3_IMPORTER_MAIN_ARTICLEINDENTIFICATIONFIELDS'                      => 'Auswahl für Artikelidentifikationsfelder',
    'D3_IMPORTER_MAIN_ARTICLEINDENTIFICATIONFIELDS_HELP'                 => 'Mit der Taste STRG können Sie mehrfach Felder selektieren, um diese unter /D³ Module/Importer/Artikelimport/Konfig./Artikelidentifikation/ bereit zu stellen.',
    'D3_IMPORTER_CONFIG_ATRUESETTINGS'                 => 'Definition von "ja" Werten',
    'D3_IMPORTER_CONFIG_AFALSESETTINGS'                => 'Definition von "nein" Werten',
    'D3_IMPORTER_CONFIG_ATRUESETTINGS_HELP'            => 'In einer CSV Datei können verschiedene Werte für einen "Aktiv"-Haken stehen.' //
        . '<br> Bsw.: Ja/Nein, true/false, 1/0, j/n, aktiv/inaktiv.' //
        . '<br>Geben Sie die einzelnen Werte zeilenweise getrennt ein, damit beim Importvorgang die Werte für den Shop interpretiert werden können.' //
        . '<br><br>Die Prüfung während des Importvorgangs erfolgt nach diesen Kriterien:' //
        . '<ul><li>Groß- und Kleinschreibung wird beachtet<li>' //
        . '<li>Zahlen werden als Zahlen interpretiert: "1" ist nicht die Zeichenkette "eins"<li>' //
        . '</ul>' //
        . 'Vorgegebene Werte:<br>' //
        . 'Ja Feld:<br>true<br>TRUE<br><br>',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_CHOOSE'                              => 'Bitte wählen Sie eine Identifikation aus!',
    'D3_IMPORTER_PICTURE_PICSPERTICK'                                    => 'Start des nächsten Bilddurchlaufes:',
    'D3_IMPORTER_PICTURE_PICSPERTICK_HELP'                               => 'Der Ablauf eines Bildimports ist wie folgt (grobe Umschreibung): ' //
        . '<ol><li>Alle Bilder aus dem Bildimportverzeichnis werden eingelesen.</li>' //
        . '<li>Pro Bild(name) wird in der Datenbank (oxarticles__d3importpic1-XX) nach einer Zuordnung gesucht.</li>' //
        . '<li>Werden alle Kriterien erfüllt, gibt es einen oder mehrere Treffer, die daraufhin importiert werden.</li></ol>',
    'D3_IMPORTER_PICTURE_MAXPICTURECOUNT'                                => 'nach',
    'D3_IMPORTER_PICTURE_MAXPICTURECOUNT_2'                              => 'gelesenen Bildern',
    'D3_IMPORTER_PICTURE_MAXPICTURECOUNT_HELP'                           => 'Nach x gelesenen Bildern wird der Durchlauf neu gestartet (auch wenn keine Bilder importiert wurden).',
    'D3_IMPORTER_PICTURE_MAXIMPORTCOUNT'                                 => 'bzw. nach ',
    'D3_IMPORTER_PICTURE_MAXIMPORTCOUNT_2'                               => 'importierten Bildern',
    'D3_IMPORTER_PICTURE_MAXIMPORTCOUNT_HELP'                            => 'Nach x importierten Bildern wird der Durchlauf neu gestartet (betrifft nur importierte Bilder).',
    'D3_IMPORTER_FAILTOSAVE_DUE_DEMO'                                    => 'Fehler: Modul ist im Testmodus und hat bereits alle Importprofil-Slots belegt.',
    'D3_IMPORTER_NOTICE_PROFILELIMITREACHED'                             => 'Hinweis: Das Modul ist im Testmodus und hat bereits alle Importprofil-Slots belegt.<br> Sie können kein weiteres Profil speichern.',
    'D3_IMPORTER_CONFIG_AARTICLESETTINGS'              => 'vordefinierte Werte für Artikelfelder',
    'D3_IMPORTER_CONFIG_AARTICLESETTINGS_HELP'         => 'Setzen Sie vordefinierte Werte, welche beim Importvorgang die <u title="Die Feldnamen können Sie der Datenbank-Tabelle oxarticles entnehmen.">Artikelfelder</u> mit den angegebenen Werten befüllt.<br>Hinweis: Werte aus der CSV Datei haben Vorrang.' //
        . '<h4>folgende Kriterien gelten:</h4><ul><li>Die Schreibweise ist "FELDNAME => WERT".</li>' //
        . '<li>Werden CSV-Daten dem vordefinierten Artikelfeld zugeordnet und sind die CSV-Daten befüllt, werden die Daten aus der CSV-Datei am Artikel gespeichert.</li></ul>' //
        . '<h4>Beispiel 1:</h4> Alle zu importierenden Artikel sollen einen Lagerstand 10 haben:<br> oxstock => 10' //
        . '<h4>Beispiel 2:</h4> Alle zu importierenden Artikel sollen inaktiv gesetzt sein:<br> oxactive => 0' //
        . '<h4>Beispiel 3:</h4> Alle zu importierenden Artikel sollen inaktiv gesetzt sein und ein Lagerstand von 10 haben:<br> oxactive => 0<br>oxstock => 10',
    'D3_IMPORTER_CONFIG_IMPORTTICKER_HELP'             => 'Hier wird angegeben, wie viele Zeilen pro Importdurchlauf ' //
        . 'durchgeführt werden sollen. Stellen Sie bei umfangreichen CSV-Dateien, den Wert etwas geringer ein. ' //
        . 'Somit kann beispielsweise einem Scriptabbruch (Aufgrund zu langer Laufzeit) vorgebeugt werden.',
    'D3_IMPORTER_CONFIG_FILEHEADERCOUNT'                                 => 'Anzahl Datei-Kopfzeilen',
    'D3_IMPORTER_CONFIG_FILEHEADERCOUNT_HELP'                            => 'Hier wird angegeben, wie viele Zeilen nicht mit importiert werden sollen. ' //
        . 'Wenn in Ihrer CSV-Datei beispielsweise Überschriften oder Spaltenbezeichnungen in der ersten Zeile angegeben sind, ' //
        . 'geben Sie hier eine 1 ein, damit die erste Zeile nicht als Artikel importiert wird.',
    'D3IMPORTER_HELPLINK'                                                => 'Fragen-zu-speziellen-Modulen/Importer/',
    'D3_IMPORTER_CONFIG_OVERRIDEEXTERNPICTURES'                          => 'lokale Bilder (/import/pictures/) durch Externe überschreiben?',
    'D3_IMPORTER_CONFIG_OVERRIDEEXTERNPICTURES_HELP'                     => '<h4>Sollen lokale Bilder im Bild-Importverzeichnis (/import/pictures/) durch externe Bilder überschrieben werden?</h4>' //
        . '<b>Aktiv:</b> Sofern ein externes Bild den gleichen Namen hat, wird das lokale Bild überschrieben.<br>' //
        . '<br><b>Inaktiv:</b> Sofern ein externes Bild den gleichen Namen und eine unterschiedliche Größe zu dem lokalen Bild hat, wird der Name des externen Bilds mit einem Zusatz (DateinameZusatz.Endung) versehen.',
    'D3_IMPORTER_MAIN_CATEGORIE_INDENTIFICATIONFIELDS'                   => 'Auswahl für Kategorieidentifikationsfelder',
    'D3_IMPORTER_MAIN_CATEGORIE_INDENTIFICATIONFIELDS_HELP'              => 'Legen Sie hier fest, welche Felder als Referenz für die Kategroeigezuordung zur Verfügung stehen sollen. Standard: oxtitle',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_NAME'                                => 'Attributsname',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_VALUE'                               => 'Attributswert am Artikel',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_NEW_ATTRIBUTE_ASSIGN'                => 'neue Attributszuordung',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_ATTRIBUTE_ASSIGN'                    => 'Attributszuordung',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_NAME_HELP'                           => 'Die Attribute werden über die Titel zugeordnet.' //
        . '<br>Die Attrtibutsnamen werden sprachenabhängig angegeben.',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_VALUE_HELP'                          => 'Die Werte der Attribute können sprachabhängig angegeben werden.',
    'D3_IMPORTER_ATTRIB_DELETE_OLDSETTINGS_INFO'                         => 'Die Attributszuordnungen dieses import-Profils ist veraltet und sollte aktualisiert werden.' //
        . '<br>Lesen Sie unbedingt unseren <a href="https://faq.d3data.de/category/module/importer/" target="d3_importer_attrib"><u>FAQ Eintrag</u></a>, bevor Sie Änderungen vornehmen!',
    'D3_IMPORTER_ATTRIB_DELETE_OLDSETTINGS_BUTTON'                       => 'Zuordnungen löschen',
    'D3_IMPORTER_CONFIG_IMPORTTYPE_HELP'               => 'Wählen Sie hier den Importtyp aus.' //
        . '<ul><li>Bei <b>"Import und Update"</b> werden Artikel importiert und aktualisiert (Standard Auswahl).</li>' //
        . '<li>Bei <b>"nur Import"</b> werden Artikel nur importiert. Es werden keine vorhandenen Artikeldaten überschrieben.</li>' //
        . '<li>Bei <b>"nur Update"</b> werden Artikel nur aktualisiert. Es werden keine neuen Artikel angelegt.</li></ul>',
    'D3_IMPORTER_CONFIG_OMITLINES_HELP'                => 'Geben Sie hier die Anzahl der Zeilen an die übersprungen werden sollen.' //
        . '<br>Bspw. wenn in der CSV Datei eine Kopfzeile mit Überschriften vorhanden ist, können Sie hier eine 1 eintragen.',
    'D3_IMPORTER_CONFIG_PRICEPLUSPERCENT_HELP'         => '' //
        . '<strong>Diese Option greift nur bei dem normalen Artikelpreis (oxprice)!</strong><p>Dies ist nicht mit der Option "Importierten Artikelpreis auf x Nachkommastellen runden." kombinierbar. 
Diese sind in zwei getrennten Importvorgängen anzuwenden und auszuführen.</p>',
    'D3_IMPORTER_CONFIG_ARTNUM2OXID_HELP'              => 'Mit dieser Einstellung wird die verwendete Artikelindentifikation als interne Shop-Indentifikatiosnnummer (oxid) genutzt.' //
        . '<br>Der Shop verwaltet die eindeutigen Shopindentifikationsnummmern selbst, ' //
        . 'daher sollte die Option mit Bedacht genutzt werden.',
    'D3_IMPORTER_CONFIG_MD54OXID_HELP'                 => 'Damit kann ein ähnlicher Ident wie bei der Original-oxId erzeugt werden.' //
        . '<br>Diese Option greift nur mit der aktiven Option "Artikelidentifikationsfeld als Ident (Datenfeld "oxid") nutzen"',
    'D3_IMPORTER_CONFIG_PRICEDECIMALROUND_HELP'        => 'Geben Sie hier einen Wert ein, um den Artikelpreis zu runden.' //
        . '<b>Beispiel:</b> "2" bedeutet, dass von 12.3456 auf 12.35 oder von 1.95583 auf 1.96 gerundet wird.' //
        . '<br> bei "1" wird von 12.3456 auf 12.3 oder von 1.95583 auf 2 gerundet.' //
        . '<br><strong>Diese Option greift nur bei dem normalen Artikelpreis (oxprice)!</strong>
<p>Dies ist nicht mit der Option "Importierten Artikelpreis um x % erhöhen." kombinierbar. Diese sind in zwei getrennten Importvorgängen anzuwenden und auszuführen.</p>',
    'D3_IMPORTER_CONFIG_AFALSESETTINGS_HELP'           => 'In einer CSV Datei können verschiedene Werte für einen "Aktiv"-Haken stehen.' //
        . '<br> Bsw.: Ja/Nein, true/false, 1/0, j/n, aktiv/inaktiv.' //
        . '<br>Geben Sie die einzelnen Werte zeilenweise getrennt ein, damit beim Importvorgang die Werte für den Shop interpretiert werden können.' //
        . '<br><br>Die Prüfung während des Importvorgangs erfolgt nach diesen Kriterien:' //
        . '<ul><li>Groß- und Kleinschreibung wird beachtet<li>' //
        . '<li>Zahlen werden als Zahlen interpretiert: "1" ist nicht die Zeichenkette "eins"<li>' //
        . '</ul>' //
        . 'Vorgegebene Werte:<br>' //
        . 'Nein Feld:<br>false<br>FALSE',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXACTIVEFROM'      => 'Aktiv von',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXACTIVETO'        => 'Aktiv bis',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXARTNUM'          => 'Artikelnummer',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXTITLE'           => 'Titel',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXID'              => 'interne Identnr.',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSHOPID'          => 'Shop Identnr.',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPARENTID'        => 'Identnr. Hauptartikel',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXACTIVE'          => 'Aktiv',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSHORTDESC'       => 'Kurzbeschreibung',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXLONGDESC'        => 'Langtext',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPRICE'           => 'Preis',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXBLFIXEDPRICE'    => 'oxblfixedprice',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPRICEA'          => 'Preis A',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPRICEB'          => 'Preis B',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPRICEC'          => 'Preis C',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXBPRICE'          => 'Bruttopreis',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXTPRICE'          => 'Alter Preis',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXEXTURL'          => 'Externe URL',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUNITNAME'        => 'Einheit',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUNITQUANTITY'    => 'Mengeneinheit',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXURLDESC'         => 'URL Beschreibung',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXURLIMG'          => 'Bild für externe URL',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVAT'             => 'Artikel MwSt.',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXTHUMB'           => 'Vorschaubild',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXICON'            => 'Icon',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_PICTURES'          => 'Artikelbilder',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC1'            => 'Bild1',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC2'            => 'Bild2',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC3'            => 'Bild3',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC4'            => 'Bild4',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC5'            => 'Bild5',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC6'            => 'Bild6',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC7'            => 'Bild7',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC8'            => 'Bild8',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC9'            => 'Bild9',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC10'           => 'Bild10',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC11'           => 'Bild11',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXPIC12'           => 'Bild12',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXZOOM1'           => 'Zoom Bild 1',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXZOOM2'           => 'Zoom Bild 2',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXZOOM3'           => 'Zoom Bild 3',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXZOOM4'           => 'Zoom Bild 4',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXWEIGHT'          => 'Gewicht',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSTOCK'           => 'Lagerbestand',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSTOCKACTIVE'     => 'Lagerverwaltung aktiv',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSTOCKFLAG'       => 'Lieferstatus',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXDELIVERY'        => 'Ausgeliefert am',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXINSERT'          => 'Angelegt am',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXTIMESTAMP'       => 'Letzte Änderung',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXLENGTH'          => 'Länge',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXWIDTH'           => 'Breite',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXHEIGHT'          => 'Höhe',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXFILE'            => 'Datei',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSEARCHKEYS'      => 'Suchbegriffe',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXTEMPLATE'        => 'Alt. Template',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXQUESTIONEMAIL'   => 'E-Mail bei Frage',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXISSEARCH'        => 'Kann gesucht werden',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXISCONFIGURABLE'  => 'Artikel ist individualisierbar',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVARNAME'         => 'Name der Variante',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVARSELECT'       => 'oxvarselect',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVARMINPRICE'     => 'Niedrigster Variantenpreis',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXFOLDER'          => 'Ordner',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSUBCLASS'        => 'oxsubclass',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSORT'            => 'Sortierung',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSOLDAMOUNT'      => 'Verkaufte Anzahl',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXNONMATERIAL'     => 'Immateriell',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXFREESHIPPING'    => 'Versandkostenfrei',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXREMINDACTIVE'    => 'Zuwenig Lagerbestand E-Mail aktiv',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXREMINDAMOUNT'    => 'Zuwenig Lagerbestand Mindestmenge',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXAMITEMID'        => 'oxamitemid',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXAMTASKID'        => 'oxamtaskid',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVENDORID'        => 'Lieferant ID',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXMANUFACTURERID'  => 'Hersteller ID',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVARCOUNT'        => 'Varianten Anzahl',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSHOPINCL'        => 'Shop einschließen',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSHOPEXCL'        => 'Shop ausschließen',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSHOPINCL1'       => 'Shop einschließen',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSHOPEXCL1'       => 'Shop ausschließen',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXEAN'             => 'EAN',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXMPN'             => 'Hersteller-Artikelnummer',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXDISTEAN'         => 'Hersteller EAN',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSTOCKTEXT'       => 'Info falls Artikel auf Lager',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXNOSTOCKTEXT'     => 'Info falls Artikel nicht auf Lager',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSKIPDISCOUNTS'   => 'Nachlässe ignorieren',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXRATINGCNT'       => 'Bewertung Anzahl',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXRATING'          => 'Bewertung',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXRRVIEW'          => 'Ausschließlich sichtbar',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXRRBUY'           => 'Ausschließlich kaufbar',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXORDERINFO'       => 'Bestell. Info',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXSEOID'           => 'SEOID',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXMINDELTIME'      => 'Min. Lieferzeit',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXMAXDELTIME'      => 'Max. Lieferzeit',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXDELTIMEUNIT'     => 'Lieferzeit Einheit',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUPDATEPRICE'     => 'Preis aktualisieren auf',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUPDATEPRICEA'    => 'Preis A aktualisieren auf',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUPDATEPRICEB'    => 'Preis B aktualisieren auf',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUPDATEPRICEC'    => 'Preis C aktualisieren auf',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXUPDATEPRICETIME' => 'Zeitpunkt der Preisaktualisierung',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXISDOWNLOADABLE'  => 'Ist herunterladbar',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVPE'             => 'Verpackungseinheit',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXBUNDLEID'        => 'Bundle Identnr.',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVARSTOCK'        => 'Varianten Lagerbestand',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTFLAG'      => 'Importflag',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPROFILEID' => 'Importprofil-ID',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC1'      => 'Bild Importfeld 1',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC2'      => 'Bild Importfeld 2',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC3'      => 'Bild Importfeld 3',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC4'      => 'Bild Importfeld 4',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC5'      => 'Bild Importfeld 5',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC6'      => 'Bild Importfeld 6',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC7'      => 'Bild Importfeld 7',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC8'      => 'Bild Importfeld 8',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC9'      => 'Bild Importfeld 9',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC10'     => 'Bild Importfeld 10',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC11'     => 'Bild Importfeld 11',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC12'     => 'Bild Importfeld 12',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC13'     => 'Bild Importfeld 13',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC14'     => 'Bild Importfeld 14',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC15'     => 'Bild Importfeld 15',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC16'     => 'Bild Importfeld 16',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC17'     => 'Bild Importfeld 17',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC18'     => 'Bild Importfeld 18',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC19'     => 'Bild Importfeld 19',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3IMPORTPIC20'     => 'Bild Importfeld 20',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3OQM_PACKAGE'     => 'Verpackungseinheit - D³ Bestellmengen Manager',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3OQM_MINIMUM'     => 'Minimum - D³ Bestellmengen Manager',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_D3OQM_MAXIMUM'     => 'Maximum - D³ Bestellmengen Manager',
    'D3_IMPORTER_CONFIG_ASSIGNIDENT_OXVARMAXPRICE'     => 'Höchster Variantenpreis',
    'D3_IMPORTER_ATTRIB_LEGEND'                                          => 'Legende:',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_ATTRIBUTE_ASSIGN_HELP'               => 'Sie können mehrere Attribute importieren.' //
        . '<br>Jede Attributszuordnung wird als Attribut angesehen. D.h. für 1 Attribut darf nur eine Attributszuordnung verwendet werden.',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_LANGUAGE'                            => '[Sprache] Aktiv/Inaktiv',
    'D3_IMPORTER_ATTRIB_IMPORTCOLUM_LANGUAGE_HELP'                       => 'Es werden Ihnen Zuweisungen für alle Sprachen angeboten.' //
        . '<br>Aktiv/<del>Aktiv</del> zeigt ob die Sprache im Shop aktiviert ist.',
    'D3_IMPORTER_ATTRIB_DELETE_OLDSETTINGS_QUESTION'                     => 'Wollen Sie die veralteten Zuordnungen wirklich löschen?',
    'D3_IMPORTER_UPDATE_OLD_ATTIBUTES_REMOVED'                                        => 'Mit der Version 4.4.1.0 wurden die Attributzuordnungen geändert.' //
        . PHP_EOL . 'Ab der Version 4.5.0.0 werden die alten Attributszuordnungen nicht mehr unterstützt!'//
        . PHP_EOL . 'Bitte lesen Sie unseren FAQ Eintrag!: https://faq.d3data.de/module/importer/anleitung-zur-umstellung-von-attributszuordnungen/'
        . PHP_EOL . 'Der Beitrag schildert die Änderungen von den alten Zuordnung zu der neuen mehrsprachigen Zuordnungen',
    'D3_IMPORTER_ATTRIB_LANGUAGE_ACTIVE'                                 => 'Aktiv',
    'D3_IMPORTER_ATTRIB_LANGUAGE_INACTIVE'                               => 'Inaktiv',
    /* Artikel verwalten -> Kategorien -> Stamm -> Schnellsortierung */
    'GENERAL_ARTICLE_D3IMPORTFLAG'                                       => 'Importflag D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPROFILEID'                                  => 'Importprofil-ID D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC1'                                       => 'Bild Importfeld 1 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC2'                                       => 'Bild Importfeld 2 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC3'                                       => 'Bild Importfeld 3 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC4'                                       => 'Bild Importfeld 4 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC5'                                       => 'Bild Importfeld 5 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC6'                                       => 'Bild Importfeld 6 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC7'                                       => 'Bild Importfeld 7 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC8'                                       => 'Bild Importfeld 8 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC9'                                       => 'Bild Importfeld 9 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC10'                                      => 'Bild Importfeld 10 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC11'                                      => 'Bild Importfeld 11 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC12'                                      => 'Bild Importfeld 12 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC13'                                      => 'Bild Importfeld 13 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC14'                                      => 'Bild Importfeld 14 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC15'                                      => 'Bild Importfeld 15 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC16'                                      => 'Bild Importfeld 16 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC17'                                      => 'Bild Importfeld 17 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC18'                                      => 'Bild Importfeld 18 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC19'                                      => 'Bild Importfeld 19 D³ Importer',
    'GENERAL_ARTICLE_D3IMPORTPIC20'                                      => 'Bild Importfeld 20 D³ Importer',
    'D3_IMPORTER_IMPORT_TESTLICENCE_NOTICE'                              => 'Das Modul ist als Testversion lizenziert.<br>Derzeit können begrenzt Artikel/Bilder importiert und Profile angelegt werden.',
    'd3mxdesc'                                                           => 'Artikelfelder',
    'd3_d3importer_controllers_admin_desc_itemmain'                      => 'Artikelfeld editieren',
    'D3_D3IMPORTERDESC_MENUSUBITEM'                                      => 'Artikelfeld editieren',
    'D3IMPORTERDESC_NEW'                                                 => 'neues Artikelfeld',
    'D3IMPORTERDESC_OXISDISABLED'                                        => 'aktiv',
    'HELP_D3IMPORTERDESC_OXISDISABLED'                                   => 'De/Aktivieren Sie das Artikelfeld für die Adminoberfläche des Importers',
    'D3IMPORTERDESC_OXFIELD'                                             => 'Datenbankfeldname',
    'HELP_D3IMPORTERDESC_OXFIELD'                                        => 'Tragen Sie hier den Name des Datenbankfelds von oxarticles oder oxartextends ein.',
    'D3IMPORTERDESC_OXDESC'                                              => 'Artikelfeld Sprache 1',
    'HELP_D3IMPORTERDESC_OXDESC'                                         => 'Geben Sie dem Artikelfeld einen lesbaren Namen in der Sprache 1 an.',
    'D3IMPORTERDESC_OXDESC_1'                                            => 'Artikelfeld Sprache 2',
    'HELP_D3IMPORTERDESC_OXDESC_1'                                       => 'Geben Sie dem Artikelfeld einen lesbaren Namen in der Sprache 2 an.',
    'D3IMPORTERDESC_OXORDER'                                             => 'Sortierung',
    'HELP_D3IMPORTERDESC_OXORDER'                                        => 'Hier können Sie die Sortierreihenfolge für den Admin festlegen.<br>' //
        . ' Oft benutzte Artikelfelder können mit einer niedrigen Zahl weiter oben angezeigt werden.',
    'D3IMPORTERDESC_OXISPIC'                                             => 'Bild',
    'HELP_D3IMPORTERDESC_OXISPIC'                                        => 'De/Aktivieren Sie das Artikelfeld für die Adminoberfläche des Bildimports (neue Felder werden im Admin nicht angezeigt).',
    'HELP_D3IMPORTERDESC'                                                => 'Hier können Sie Artikelfelder für den Importer bearbeiten.<br>'//
        . 'Die Artikelfelder werden an verschiedenen Stellen im Importer genutzt (Artikelimport/Artikelfelder, Einstellungen/Auswahl für Artikelidentifikationsfelder). <br>'//
        . 'Damit können Sie die Auswahl der benötigten Felder im Admin verringern oder neue Felder hinzufügen.',
    'D3_IMPORTER_PRICE2ART_PERCENTOPTION'                                => 'ist % Rabatt Preis?',
    'HELP_D3_IMPORTER_PRICE2ART_PERCENTOPTION'                           => 'Wenn diese Option gesetzt ist, wird der Preis als prozentualer Preis abgespeichert. Mehr Infos finden Sie im Admin unter /Artikel verwalten/Artikel/Lager/Staffelpreise/.',
    'HELP_D3_IMPORTER_PRICE2ART_PRICE'                                   => 'Hinterlegen Sie einen Preis für die Staffel (Kommas werden durch einen Punkt ersetzt, daher vorsicht bei 1,234.56 Angaben. Besser: 1234,56 oder 1234.56).<br><br>Um prozentuale Staffelpreise zu importieren, nutzen Sie das % Zeichen dazu. Bspw: 10% oder 1,23% oder 1.23%
<p>Die Rundung wird durch die Option "Nicht ganzzahlige Eingaben bei Artikelmengen erlauben (z.B. 1,5)" unter Stammddaten --> Grundeinstellungen --> Einstellungen --> Bestellungen gesteuert.</p>',
    'D3_PICTURE_IMPORT_LOAD_PROFILE'                                     => 'Bitte wählen Sie ein Importprofil aus.',
    'HELP_D3_PICTURE_EXTPICTURE_START'                                   => 'Setzen Sie den Haken, wenn die zu importierenden Bilder auf externen URL\'s vorliegen. <br>Bspw.: https://placeimg.com/1000/1000/any.jpg.' //
        . '<br><br>Der Bildimport wird die URL\'s aufrufen und die Bilder in das definierte Bildverzeichnis herunterladen.',
    'D3_IMPORTER_PICTURE_IMPORT_STEP1'                                   => 'Schritt 1:',
    'D3_IMPORTER_PICTURE_IMPORT_STEP2'                                   => 'Schritt 2:',
    'D3_IMPORTER_FIELDS_CHECKALL'                                        => 'alle Updatehaken setzen/entfernen',
    'D3_IMPORTER_CONFIG_BLDELETEMASTERPICTURE'                           => 'Masterbilder am Artikel vorher entfernen (empfohlen)',
    'D3_IMPORTER_CONFIG_BLDELETEMASTERPICTURE_HELP'                      => 'Aktivieren Sie diese Option, um Bilder-Altlasten auf dem Server zu vermeiden.<br>'.PHP_EOL
        .'Währenddes Importvorgang\'s werden vorherige Artikelbilder, über den Shop gelöscht.<br>'.PHP_EOL
        .'Die Löschung umfasst die artikelbezogenen Bilder im "/master/" und die generierten Bilder im "/generated/" Verzeichnis.<br>'.PHP_EOL
        .'<br>'.PHP_EOL
        .'Deaktivieren Sie diese Option, so werden die Bilder direkt importiert.<br>'.PHP_EOL
        .'Es können dabei in den /master/product/*/ Verzeichnissen ungenutzte Bilddateien entstehen.',
    'D3_IMPORTER_CONFIG_PATHTOMOVE'                                      => 'Aktion nachdem ein Bild importiert wurde:',
    'D3_IMPORTER_CONFIG_PATHTOMOVE_HELP'                                 => 'Wählen Sie eine entsprechende Option aus, damit die Bilder im import/pictures/ Verzeichnis gelöscht oder in ein anzugebendes Verzeichnis verschoben werden.<br>'
        .'Das Verzeichnis ist mit absoluten Pfad anzugeben, bspw: /var/www/myshop.de/{VerzeichnisName}/',
    'D3_IMPORTER_CONFIG_PICTURESACTIONAFTERIMPORT_DELETE'                => 'Bild löschen',
    'D3_IMPORTER_CONFIG_PICTURESACTIONAFTERIMPORT_MOVE'                  => 'Bild in Verzeichnis verschieben',
    'D3_IMPORTER_CONFIG_FOLDER'                                          => 'absoluter Pfad zum Zielverzeichnis',
    'D3_IMPORTER_CONFIG_FOLDER_HELP'                                     => 'Tragen Sie hier den absoluten Pfad des Zielverzeichnis ein. Stellen Sie sicher, dass das Zielverzeichnis vorhanden und beschreibbar ist.',

    'D3_IMPORTER_SETUP_CREATEDIRECTORY'                                  => 'Legen Sie das Verzeichnis "%s" neu an.',
);
